# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VhkScCKxRU6DZJWesG8N4qxtbxzrMw3Z
"""

!pip install groq fpdf2 pillow streamlit pyngrok -q

from google.colab import drive
drive.mount('/content/drive')

# -*- coding: utf-8 -*-
import os, warnings, re, base64, json, tempfile
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
warnings.filterwarnings('ignore')

import cv2
import numpy as np
import tensorflow as tf
tf.get_logger().setLevel('ERROR')
tf.autograph.set_verbosity(0)

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

import streamlit as st
from datetime import datetime
from fpdf import FPDF
from groq import Groq

# ════════════════════════════════════════════════════
# PAGE CONFIG
# ════════════════════════════════════════════════════
st.set_page_config(
    page_title="NeuroScan AI",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ════════════════════════════════════════════════════
# DARK THEME CSS
# ════════════════════════════════════════════════════
st.markdown("""
<style>
[data-testid="stAppViewContainer"] { background: #0d0f14; color: #c9cdd6; }
[data-testid="stHeader"]           { background: #111318; border-bottom: 1px solid #1e2330; }
[data-testid="stSidebar"]          { background: #111318 !important; border-right: 1px solid #1e2330; }
.block-container                   { padding: 1.5rem 2rem 2rem; }
div[data-testid="metric-container"] {
    background: #111318; border: 1px solid #1e2330;
    border-radius: 10px; padding: 12px 16px;
}
div[data-testid="metric-container"] label {
    color: #4a6fa5 !important; font-size: 11px;
    text-transform: uppercase; letter-spacing: 0.08em;
}
div[data-testid="stMetricValue"] { color: #7ab8ff; font-size: 22px; font-weight: 700; }
[data-testid="stFileUploadDropzone"] {
    background: #0d1520 !important;
    border: 1.5px dashed #1e2d4a !important;
    border-radius: 10px !important;
}
.stButton > button {
    background: #1a3a70 !important; color: #7ab8ff !important;
    border: 1px solid #1e4080 !important; border-radius: 8px !important;
    font-weight: 600 !important; width: 100%;
}
.stButton > button:hover { background: #1f4585 !important; border-color: #4a9eff !important; }
[data-testid="stDownloadButton"] > button {
    background: #0f2a10 !important; color: #4dc86f !important;
    border: 1px solid #1a4020 !important; border-radius: 8px !important;
    font-weight: 600 !important; width: 100%;
}
.streamlit-expanderHeader {
    background: #111318 !important; color: #c9cdd6 !important;
    border: 1px solid #1e2330 !important; border-radius: 8px !important;
}
.streamlit-expanderContent {
    background: #111318 !important; border: 1px solid #1e2330 !important;
    border-radius: 0 0 8px 8px !important;
}
hr { border-color: #1e2330 !important; }
[data-testid="stDataFrame"] { border: 1px solid #1e2330; border-radius: 10px; }
[data-testid="stAlert"]      { background: #111318 !important; border: 1px solid #1e2330 !important; border-radius: 8px !important; }
div[data-testid="stSuccess"] { border-left: 3px solid #4dc86f !important; }
div[data-testid="stError"]   { border-left: 3px solid #e8604a !important; }
div[data-testid="stWarning"] { border-left: 3px solid #d4a843 !important; }
div[data-testid="stInfo"]    { border-left: 3px solid #4a9eff !important; }
section[data-testid="stSidebar"] p,
section[data-testid="stSidebar"] label { color: #7a8299; }
section[data-testid="stSidebar"] h1,
section[data-testid="stSidebar"] h2,
section[data-testid="stSidebar"] h3 { color: #4a6fa5; }
[data-testid="stImage"] img { border-radius: 8px; border: 1px solid #1e2330; }
h2, h3 { color: #e2e5ed !important; }
p, li  { color: #9099b0; }
.tag-red   { background:#2a1010; color:#e87060; border:1px solid #3a1818; padding:2px 8px; border-radius:4px; font-size:11px; font-weight:700; }
.tag-amber { background:#221a08; color:#d4a843; border:1px solid #3a2c0a; padding:2px 8px; border-radius:4px; font-size:11px; font-weight:700; }
.tag-green { background:#0f2a10; color:#4dc86f; border:1px solid #1a4020; padding:2px 8px; border-radius:4px; font-size:11px; font-weight:700; }
.tag-blue  { background:#0d1a2a; color:#4a9eff; border:1px solid #1a2e4a; padding:2px 8px; border-radius:4px; font-size:11px; font-weight:700; }
</style>
""", unsafe_allow_html=True)

# ════════════════════════════════════════════════════
# CONFIG
# ════════════════════════════════════════════════════
BASE_DIR         = "/content/drive/MyDrive/Project work"
CLASS_MODEL_PATH = BASE_DIR + "/models/Classification/Tumor_v2s_clean.keras"
SEG_MODEL_PATH   = BASE_DIR + "/models/Segmentation/unet_lgg_segmentation_u-net.keras"
REPORT_DIR       = BASE_DIR + "/Reports"
HISTORY_FILE     = BASE_DIR + "/case_history.json"
os.makedirs(REPORT_DIR, exist_ok=True)

GROQ_API_KEY     = ""

IMG_SIZE         = 384
SEG_SIZE         = 256
CLASS_NAMES      = ["glioma", "meningioma", "no_tumor", "pituitary"]
PIXEL_SPACING_MM = 0.5
MM2_TO_CM2       = 0.01
MRI_PARAMS = {
    "sequence":        "T1-Weighted Contrast Enhanced",
    "resolution":      "384 x 384",
    "slice_thickness": "5.0 mm",
    "field_strength":  "1.5T",
    "voxel_size":      "0.5 x 0.5 x 5.0 mm",
}

# ════════════════════════════════════════════════════
# MODEL LOADING
# ════════════════════════════════════════════════════
@st.cache_resource(show_spinner="Loading AI models...")
def load_models():
    cm   = tf.keras.models.load_model(CLASS_MODEL_PATH)
    sm   = tf.keras.models.load_model(SEG_MODEL_PATH, compile=False)
    base = cm.get_layer("efficientnetv2-s")
    heads = []
    hit   = False
    for layer in cm.layers:
        if layer.name == "efficientnetv2-s":
            hit = True
            continue
        if hit:
            heads.append(layer)
    return cm, sm, base, heads

# ════════════════════════════════════════════════════
# PIPELINE FUNCTIONS
# ════════════════════════════════════════════════════
def safe(text):
    if not isinstance(text, str): text = str(text)
    for c, r in {
        '\u2014':'-','\u2013':'-','\u2012':'-','\u2010':'-','\u2011':'-',
        '\u2018':"'",'\u2019':"'",'\u201c':'"','\u201d':'"',
        '\u2022':'-','\u2026':'...','\u00b2':'2','\u00b3':'3',
        '\u00b0':' deg','\u00b1':'+/-','\u2192':'->','\u2265':'>=',
        '\u2264':'<=','\u2260':'!=','\u00b5':'u','\u00d7':'x',
    }.items():
        text = text.replace(c, r)
    return text.encode('latin-1', errors='ignore').decode('latin-1')

def load_class_image(path):
    from tensorflow.keras.applications.efficientnet_v2 import preprocess_input as effv2_prep
    img = tf.keras.utils.load_img(path, target_size=(IMG_SIZE, IMG_SIZE))
    img = tf.keras.utils.img_to_array(img)
    img = effv2_prep(img)
    return np.expand_dims(img, axis=0)

def get_gradcam_heatmap(img_tensor, base_model, head_layers):
    img_tensor_cast = tf.cast(img_tensor, tf.float32)
    conv_output     = base_model(img_tensor_cast, training=False)
    conv_var        = tf.Variable(conv_output)
    with tf.GradientTape() as tape:
        tape.watch(conv_var)
        x = conv_var
        for layer in head_layers:
            x = layer(x)
        class_score = x[:, tf.argmax(x[0])]
    grads = tape.gradient(class_score, conv_var)
    if grads is None: return np.zeros((12, 12))
    pooled = tf.reduce_mean(grads, axis=(0, 1, 2))
    hmap   = conv_output[0] @ pooled[..., tf.newaxis]
    hmap   = tf.squeeze(hmap)
    hmap   = tf.maximum(hmap, 0) / (tf.math.reduce_max(hmap) + 1e-8)
    return hmap.numpy()

def estimate_tumor_size(mask):
    tp   = int(np.sum(mask))
    tot  = mask.shape[0] * mask.shape[1]
    amm2 = tp * (PIXEL_SPACING_MM ** 2)
    acm2 = amm2 * MM2_TO_CM2
    dcm  = (2 * np.sqrt(amm2 / np.pi)) / 10
    pct  = (tp / (tot * 0.60)) * 100
    vol  = acm2 * (5.0 / 10)
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    bbox = None
    if cnts:
        x, y, w, h = cv2.boundingRect(max(cnts, key=cv2.contourArea))
        bbox = {"x": x, "y": y, "w": w, "h": h,
                "width_cm":  round(w * PIXEL_SPACING_MM / 10, 2),
                "height_cm": round(h * PIXEL_SPACING_MM / 10, 2)}
    return {"tumor_pixels": tp, "area_mm2": round(amm2, 2), "area_cm2": round(acm2, 4),
            "diameter_cm": round(dcm, 3), "tumor_percent": round(pct, 2),
            "volume_cm3": round(vol, 3), "bbox": bbox}

def analyze_tumor_shape(mask):
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not cnts: return None
    lg   = max(cnts, key=cv2.contourArea)
    area = cv2.contourArea(lg)
    peri = cv2.arcLength(lg, True)
    if area == 0 or peri == 0: return None
    irr  = min(round(1 - (4 * np.pi * area) / (peri ** 2), 3), 1.0)
    comp = round((peri ** 2) / (4 * np.pi * area), 3)
    hull = cv2.convexHull(lg)
    conv = round(area / cv2.contourArea(hull), 3) if cv2.contourArea(hull) > 0 else 1.0
    ecc  = 0.0
    if len(lg) >= 5:
        el  = cv2.fitEllipse(lg)
        a, b = el[1][0] / 2, el[1][1] / 2
        if max(a, b) > 0: ecc = round(np.sqrt(1 - (min(a, b) / max(a, b)) ** 2), 3)
    bdef  = "Poorly defined" if irr > 0.5 else ("Moderately defined" if irr > 0.3 else "Well-defined")
    rough = "High" if irr > 0.5 else ("Moderate" if irr > 0.3 else "Low")
    return {"irregularity": irr, "compactness": comp, "convexity": conv,
            "eccentricity": ecc, "border_def": bdef, "roughness": rough}

def detect_mass_effect(mask):
    h, w = mask.shape
    mid  = w // 2
    lt   = int(np.sum(mask[:, :mid]))
    rt   = int(np.sum(mask[:, mid:]))
    tot  = lt + rt
    lat  = "None"; smm = 0.0
    if tot > 0:
        r   = lt / tot
        lat = "Left hemisphere" if r > 0.6 else ("Right hemisphere" if r < 0.4 else "Bilateral/Midline")
        smm = round(abs(lt - rt) * (PIXEL_SPACING_MM ** 2) / (h * PIXEL_SPACING_MM), 2)
    comp = "Moderate" if smm > 5 else ("Mild" if smm > 2 else "None")
    sulf = "Present" if smm > 2 else "Absent"
    return {"laterality": lat, "shift_mm": smm, "compression": comp, "sulcal": sulf}

def compute_risk_score(label, confidence, size_info, shape_info, mass_info):
    if label == "no_tumor": return {"score": 0.0, "risk": "None", "progression_risk": "0%"}
    s  = min(confidence, 1.0) * 0.25
    s += min(size_info['tumor_percent'] / 30, 1.0) * 0.20
    s += min(size_info['volume_cm3'] / 20, 1.0) * 0.20
    if shape_info:
        s += shape_info['irregularity'] * 0.15
        s += (1 - shape_info['convexity']) * 0.10
    s += min(mass_info['shift_mm'] / 10, 1.0) * 0.10
    s  = round(min(s, 1.0), 3)
    risk = "High" if s > 0.7 else ("Moderate" if s > 0.4 else "Low")
    prog = f"{int(s*100)}%" if s > 0.7 else (f"{int(s*80)}%" if s > 0.4 else f"{int(s*60)}%")
    return {"score": s, "risk": risk, "progression_risk": prog}

def compute_confidence_calibration(confidence):
    u = round((1 - confidence) * 0.5 + 0.01, 3)
    return {"uncertainty": f"+/-{round(u*100,1)}%", "cal_score": round(1 - u, 3)}

def get_severity(label, confidence, tumor_percent):
    if label == "no_tumor": return "None"
    if tumor_percent > 20 or confidence > 0.95: return "Severe"
    if tumor_percent > 10 or confidence > 0.80: return "Moderate"
    return "Mild"

def get_recommendation(label, severity):
    if label == "no_tumor": return "No tumor detected. Routine follow-up recommended."
    return {"Mild":     "Follow-up MRI in 3 months. Neurology consult.",
            "Moderate": "Urgent neurology consultation within 2 weeks.",
            "Severe":   "Immediate neurosurgical referral required."}.get(severity, "Consult specialist.")

def get_clinical_decision(label, severity, mass_info):
    if label == "no_tumor":
        return {"steps": ["Routine follow-up in 12 months", "No immediate action required"], "urgency": "Low"}
    steps = ["Neurosurgical consultation", "Contrast MRI follow-up"]
    if severity == "Severe":
        steps += ["MR Spectroscopy", "Perfusion MRI", "Surgical planning", "Biopsy / Histopathology"]
        urg = "Critical"
    elif severity == "Moderate":
        steps += ["MR Spectroscopy", "Neuropsychological assessment"]
        urg = "High"
    else:
        steps += ["PET scan consideration", "Neurological evaluation"]
        urg = "Moderate"
    if mass_info['shift_mm'] > 3: steps.append("Immediate review for mass effect")
    return {"steps": steps, "urgency": urg}

def get_rano_assessment(label, size_info, shape_info):
    if label == "no_tumor": return None
    sc  = "Large" if size_info['diameter_cm'] > 3 else ("Medium" if size_info['diameter_cm'] > 1.5 else "Small")
    nec = "Likely present" if (shape_info and shape_info['irregularity'] > 0.5) else "Not clearly identified"
    enh = "Heterogeneous" if (shape_info and shape_info['irregularity'] > 0.4) else "Homogeneous"
    grd = "High-Grade (imaging features suggest possible high-grade - histopathological confirmation required)"
    if size_info['diameter_cm'] < 2 and (not shape_info or shape_info['irregularity'] < 0.3):
        grd = "Low-Grade (imaging features suggest possible low-grade - histopathological confirmation required)"
    return {"size_cat": sc, "enhancement": enh, "necrosis": nec, "grade": grd}

def clean_llm_text(text):
    text = re.sub(r'#{1,6}\s*', '', text)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'`(.*?)`', r'\1', text)
    return safe(text)

def generate_llm_report(image_path, label, confidence, size_info, shape_info,
                         mass_info, risk_info, severity, recommendation, rano):
    groq_client = Groq(api_key=GROQ_API_KEY)
    with open(image_path, "rb") as f:
        img_b64 = base64.b64encode(f.read()).decode("utf-8")
    bbox_t  = f"{size_info['bbox']['width_cm']} cm x {size_info['bbox']['height_cm']} cm" if size_info['bbox'] else "N/A"
    rano_t  = "" if not rano else f"\n- RANO Size: {rano['size_cat']}\n- Enhancement: {rano['enhancement']}\n- Necrosis: {rano['necrosis']}"
    shape_t = "" if not shape_info else f"\n- Irregularity: {shape_info['irregularity']}\n- Border: {shape_info['border_def']}"
    prompt  = f"""You are an expert radiologist AI assistant.

AI FINDINGS:
- Type: {label} | Confidence: {confidence:.2%} | Severity: {severity}
- Area: {size_info['area_cm2']} cm2 | Diameter: {size_info['diameter_cm']} cm | Volume: {size_info['volume_cm3']} cm3
- Brain Coverage: {size_info['tumor_percent']}% | Bounding Box: {bbox_t}
- Laterality: {mass_info['laterality']} | Midline Shift: {mass_info['shift_mm']} mm
- Risk Score: {risk_info['score']} | Growth Risk: {risk_info['risk']}
{shape_t}{rano_t}

Write a structured radiology report with these exact 6 sections:
1. CLINICAL INDICATION
2. IMAGING TECHNIQUE
3. FINDINGS
4. IMPRESSION
5. SEVERITY ASSESSMENT
6. RECOMMENDATIONS

STRICT RULES:
- Plain ASCII only. No em dashes, smart quotes, markdown, bullets, or special symbols.
- Never confirm tumor grade. Say imaging features suggest possible grade only.
- Always state histopathological confirmation is required.
- Keep each section to 2-4 sentences. Total report under 300 words."""
    resp = groq_client.chat.completions.create(
        model="meta-llama/llama-4-scout-17b-16e-instruct",
        messages=[{"role": "user", "content": [
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}},
            {"type": "text", "text": prompt}
        ]}],
        max_tokens=1000
    )
    return clean_llm_text(resp.choices[0].message.content)

def generate_normal_llm_report(image_path, confidence):
    """Generate a clean normal brain MRI report when no tumor is detected."""
    groq_client = Groq(api_key=GROQ_API_KEY)
    with open(image_path, "rb") as f:
        img_b64 = base64.b64encode(f.read()).decode("utf-8")
    prompt = f"""You are an expert radiologist AI assistant.

AI FINDINGS:
- Classification: No Tumor Detected
- Confidence: {confidence:.2%}
- All brain structures appear within normal limits.

Write a structured normal brain MRI radiology report with these exact 6 sections:
1. CLINICAL INDICATION
2. IMAGING TECHNIQUE
3. FINDINGS
4. IMPRESSION
5. SEVERITY ASSESSMENT
6. RECOMMENDATIONS

STRICT RULES:
- Plain ASCII only. No em dashes, smart quotes, markdown, bullets, or special symbols.
- State clearly that no intracranial mass or tumor is identified.
- Describe normal brain findings.
- Recommend routine follow-up only.
- Keep each section to 2-3 sentences. Total report under 250 words."""
    resp = groq_client.chat.completions.create(
        model="meta-llama/llama-4-scout-17b-16e-instruct",
        messages=[{"role": "user", "content": [
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}},
            {"type": "text", "text": prompt}
        ]}],
        max_tokens=800
    )
    return clean_llm_text(resp.choices[0].message.content)

def save_normal_pdf_report(filename, image_path, confidence, llm_report, orig):
    """Simple 2-page PDF for no_tumor cases — no segmentation, no charts."""
    NAV   = (20, 40, 74);  TEXT  = (30, 35, 45);  LGREY = (200, 205, 210)
    MUTED = (100, 110, 125); BG  = (245, 247, 250); WHT   = (255, 255, 255)
    GREEN = (0, 120, 60)

    pdf = FPDF(); pdf.set_auto_page_break(auto=False)
    pdf.add_page()

    def draw_header(title, sub1, sub2=""):
        pdf.set_fill_color(*NAV); pdf.rect(0, 0, 210, 14, 'F')
        pdf.set_font("Helvetica", "B", 13); pdf.set_text_color(*WHT)
        pdf.set_xy(10, 1.5); pdf.cell(120, 10, safe(title))
        pdf.set_font("Helvetica", "", 7); pdf.set_text_color(180, 200, 230)
        pdf.set_xy(135, 2); pdf.cell(65, 5, safe(sub1), align="R")
        pdf.set_xy(135, 7); pdf.cell(65, 5, safe(sub2), align="R")
        pdf.set_text_color(*TEXT)

    def draw_footer(pg, total):
        pdf.set_xy(10, 287); pdf.set_font("Helvetica", "I", 6.5); pdf.set_text_color(*MUTED)
        pdf.cell(130, 4, "AI-generated report. Must be reviewed by a qualified medical professional before clinical use.")
        pdf.set_xy(170, 287); pdf.cell(30, 4, f"Page {pg} / {total}", align="R")
        pdf.set_text_color(*TEXT)

    def section_bar(title, y):
        pdf.set_fill_color(*NAV); pdf.rect(10, y, 190, 6, 'F')
        pdf.set_font("Helvetica", "B", 7.5); pdf.set_text_color(*WHT)
        pdf.set_xy(12, y + 0.8); pdf.cell(186, 4.5, safe(title))
        pdf.set_text_color(*TEXT); return y + 7

    def card(x, y, w, h):
        pdf.set_fill_color(*BG); pdf.set_draw_color(*LGREY); pdf.rect(x, y, w, h, 'FD')

    def divider(y):
        pdf.set_draw_color(*LGREY); pdf.line(10, y, 200, y)

    # PAGE 1
    draw_header("AI Brain MRI Analysis Report", f"File: {filename}",
                f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Sequence: {MRI_PARAMS['sequence']}")

    # Green normal banner
    pdf.set_fill_color(*GREEN); pdf.rect(10, 15, 190, 8, 'F')
    pdf.set_font("Helvetica", "B", 7.5); pdf.set_text_color(*WHT)
    banner = f" RESULT: NORMAL  |  NO TUMOR DETECTED  |  CONFIDENCE: {confidence:.2%}  |  SEVERITY: NONE "
    pdf.set_xy(10, 17); pdf.cell(190, 4, safe(banner), align="C"); pdf.set_text_color(*TEXT)

    y = 24; y = section_bar("ANALYSIS SUMMARY", y)
    card(10, y, 190, 30)
    pdf.set_font("Helvetica", "B", 7); pdf.set_text_color(*MUTED)
    pdf.set_xy(12, y+3); pdf.cell(40, 5, "Classification:", ln=False)
    pdf.set_font("Helvetica", "B", 9); pdf.set_text_color(*GREEN)
    pdf.set_xy(52, y+3); pdf.cell(60, 5, "NO TUMOR DETECTED", ln=False)
    pdf.set_font("Helvetica", "B", 7); pdf.set_text_color(*MUTED)
    pdf.set_xy(12, y+11); pdf.cell(40, 5, "Confidence:", ln=False)
    pdf.set_font("Helvetica", "", 8); pdf.set_text_color(*TEXT)
    pdf.set_xy(52, y+11); pdf.cell(60, 5, f"{confidence:.2%}", ln=False)
    pdf.set_font("Helvetica", "B", 7); pdf.set_text_color(*MUTED)
    pdf.set_xy(12, y+19); pdf.cell(40, 5, "Recommendation:", ln=False)
    pdf.set_font("Helvetica", "", 8); pdf.set_text_color(*TEXT)
    pdf.set_xy(52, y+19); pdf.cell(130, 5, "Routine follow-up. No immediate action required.")
    pdf.set_text_color(*TEXT); y += 34

    y = section_bar("ORIGINAL MRI SCAN", y)
    tmp = "/tmp/report_imgs"; os.makedirs(tmp, exist_ok=True)
    orig_path = f"{tmp}/orig_normal.jpg"; cv2.imwrite(orig_path, orig)
    card(10, y, 190, 80)
    pdf.image(orig_path, x=55, y=y+4, w=100, h=72)
    y += 84

    # Disclaimer
    y = max(y, 240)
    pdf.set_fill_color(230, 255, 230); pdf.set_draw_color(80, 180, 80); pdf.rect(10, y, 190, 14, 'FD')
    pdf.set_font("Helvetica", "B", 7); pdf.set_text_color(0, 100, 0)
    pdf.set_xy(13, y+2.5); pdf.cell(10, 4.5, "(!)", ln=False)
    pdf.set_font("Helvetica", "", 7); pdf.set_xy(20, y+2.5)
    pdf.multi_cell(177, 4.5,
        "IMPORTANT: This AI-generated analysis is intended for screening and research purposes only. "
        "All findings must be reviewed by a qualified radiologist before any clinical decisions are made.")
    pdf.set_text_color(*TEXT); draw_footer(1, 2)

    # PAGE 2 — Normal Radiology Report
    pdf.add_page()
    draw_header("AI Generated Radiology Report", f"File: {filename}",
                "Note: AI-generated imaging findings. Clinical review recommended.")
    y3 = 25; divider(y3); y3 += 3
    for line in llm_report.split("\n"):
        line = safe(line.strip())
        if not line: y3 += 2; continue
        if y3 > 275: break
        is_section = any(line.startswith(h) for h in ["1.","2.","3.","4.","5.","6.","7.","8.","9."])
        if is_section:
            y3 += 2; pdf.set_fill_color(*NAV); pdf.rect(10, y3, 3.5, 6.5, 'F')
            pdf.set_fill_color(230, 235, 250); pdf.rect(14, y3, 186, 6.5, 'F')
            pdf.set_font("Helvetica", "B", 8.5); pdf.set_text_color(*NAV)
            pdf.set_xy(16, y3+0.8); pdf.cell(183, 5.5, safe(f" {line}"))
            pdf.set_text_color(*TEXT); y3 += 9
        else:
            pdf.set_font("Helvetica", "", 8); pdf.set_text_color(50, 55, 65)
            pdf.set_xy(14, y3); pdf.multi_cell(184, 4.8, line); y3 = pdf.get_y() + 1
    draw_footer(2, 2)

    safe_name = os.path.splitext(filename)[0]
    ts  = datetime.now().strftime('%Y%m%d%H%M%S')
    out = os.path.join(REPORT_DIR, f"{safe_name}_{ts}_normal_report.pdf")
    pdf.output(out)
    return out

def generate_risk_chart(size_info, risk_info, shape_info, mass_info):
    DARK = '#14284A'; RED = '#C0392B'; ORANGE = '#E67E22'; GREEN = '#27AE60'
    BLUE = '#2980B9'; PURPLE = '#8E44AD'; TEAL = '#16A085'; BG = '#F5F7FA'
    def risk_color(v):
        if v > 0.6: return RED
        if v > 0.3: return ORANGE
        return GREEN
    fig, axes = plt.subplots(1, 3, figsize=(14, 3.2))
    fig.patch.set_facecolor('#FFFFFF')
    tp = max(min(size_info['tumor_percent'], 100), 0)
    ax = axes[0]; ax.set_facecolor('#FFFFFF')
    wedges, texts, autotexts = ax.pie(
        [tp, 100 - tp], colors=[RED, GREEN], autopct='%1.1f%%', startangle=90,
        pctdistance=0.78, wedgeprops=dict(width=0.55, edgecolor='white', linewidth=2),
        textprops={'fontsize': 7.5, 'color': '#333333'})
    for at in autotexts:
        at.set_fontsize(7); at.set_fontweight('bold'); at.set_color('white')
    ax.text(0, 0, f"{tp:.1f}%\nTumor", ha='center', va='center', fontsize=8, fontweight='bold', color=DARK)
    ax.set_title('Tumor vs Brain Coverage', fontsize=9, fontweight='bold', color=DARK, pad=8)
    ax.legend(handles=[mpatches.Patch(facecolor=RED, label='Tumor'),
                        mpatches.Patch(facecolor=GREEN, label='Healthy Brain')],
               fontsize=6.5, loc='lower center', bbox_to_anchor=(0.5, -0.12), ncol=2, frameon=False)
    ax = axes[1]; ax.set_facecolor(BG)
    for sp in ax.spines.values(): sp.set_color('#DDDDDD')
    cats = ['Mass Effect', 'Shape', 'Size', 'Confidence']
    vals = [round(min(mass_info['shift_mm'] / 10, 1.0), 2),
            round(shape_info['irregularity'] if shape_info else 0, 2),
            round(min(size_info['tumor_percent'] / 30, 1.0), 2),
            round(min(risk_info['score'] * 1.2, 1.0), 2)]
    bars = ax.barh(cats, vals, color=[risk_color(v) for v in vals], height=0.45, edgecolor='white', linewidth=0.8)
    ax.set_xlim(0, 1.0); ax.set_xlabel('Score (0-1)', fontsize=7, color='#555555')
    ax.tick_params(axis='y', labelsize=7.5); ax.tick_params(axis='x', labelsize=6.5)
    ax.set_title('Risk Factor Analysis', fontsize=9, fontweight='bold', color=DARK, pad=8)
    for x in [0.3, 0.6]: ax.axvline(x, color='#CCCCCC', linewidth=0.8, linestyle='--')
    for bar, v in zip(bars, vals):
        ax.text(min(v + 0.03, 0.97), bar.get_y() + bar.get_height() / 2,
                f'{v:.2f}', va='center', ha='left', fontsize=7, fontweight='bold', color='#333333')
    ax.legend(handles=[mpatches.Patch(facecolor=RED, label='High   > 0.6'),
                        mpatches.Patch(facecolor=ORANGE, label='Mod    > 0.3'),
                        mpatches.Patch(facecolor=GREEN, label='Low   <= 0.3')],
               fontsize=6, loc='lower right', frameon=True, framealpha=0.85)
    ax = axes[2]; ax.set_facecolor(BG)
    for sp in ax.spines.values(): sp.set_color('#DDDDDD')
    if shape_info:
        labels = ['Irregularity', 'Compactness\n(norm)', 'Eccentricity', 'Inv. Convexity']
        values = [shape_info['irregularity'], min(shape_info['compactness'] / 3.5, 1.0),
                  shape_info['eccentricity'], round(1 - shape_info['convexity'], 3)]
        bars2  = ax.bar(range(len(labels)), values, color=[PURPLE, BLUE, TEAL, ORANGE],
                        width=0.55, edgecolor='white', linewidth=0.8)
        ax.set_xticks(range(len(labels))); ax.set_xticklabels(labels, fontsize=6.5)
        ax.set_ylim(0, 1.1); ax.set_ylabel('Score', fontsize=7, color='#555555')
        ax.tick_params(axis='y', labelsize=6.5)
        ax.axhline(0.5, color='#CCCCCC', linewidth=0.8, linestyle='--', label='Threshold')
        ax.legend(fontsize=6, loc='upper right', frameon=True, framealpha=0.85)
        for bar, v in zip(bars2, values):
            ax.text(bar.get_x() + bar.get_width() / 2, v + 0.02, f'{v:.2f}',
                    ha='center', fontsize=7, fontweight='bold', color='#333333')
    ax.set_title('Tumor Shape Metrics', fontsize=9, fontweight='bold', color=DARK, pad=8)
    plt.suptitle('Tumor Risk Analytics', fontsize=11, fontweight='bold', color=DARK, y=1.02)
    plt.tight_layout()
    chart_path = "/tmp/risk_chart.jpg"
    plt.savefig(chart_path, dpi=180, bbox_inches='tight', facecolor='white')
    plt.close()
    return chart_path

def save_pdf_report(filename, image_path, label, confidence,
                    size_info, shape_info, mass_info, risk_info, cal_info,
                    severity, rec, llm_report, clinical, rano,
                    orig, mask_overlay, heatmap, gradcam_overlay):
    NAV   = (20, 40, 74);   TEXT  = (30, 35, 45);   LGREY = (200, 205, 210)
    MUTED = (100, 110, 125); BG   = (245, 247, 250); WHT   = (255, 255, 255)
    SC    = (180, 30, 30) if severity in ("Severe", "Moderate") else (20, 100, 40)

    pdf = FPDF(); pdf.set_auto_page_break(auto=False)
    pdf.add_page()

    def draw_header(title, sub1, sub2=""):
        pdf.set_fill_color(*NAV); pdf.rect(0, 0, 210, 14, 'F')
        pdf.set_font("Helvetica", "B", 13); pdf.set_text_color(*WHT)
        pdf.set_xy(10, 1.5); pdf.cell(120, 10, safe(title))
        pdf.set_font("Helvetica", "", 7); pdf.set_text_color(180, 200, 230)
        pdf.set_xy(135, 2); pdf.cell(65, 5, safe(sub1), align="R")
        pdf.set_xy(135, 7); pdf.cell(65, 5, safe(sub2), align="R")
        pdf.set_text_color(*TEXT)

    def draw_footer(pg):
        pdf.set_xy(10, 287); pdf.set_font("Helvetica", "I", 6.5); pdf.set_text_color(*MUTED)
        pdf.cell(130, 4, "AI-generated report. Must be reviewed by a qualified medical professional before clinical use.")
        pdf.set_xy(170, 287); pdf.cell(30, 4, f"Page {pg} / 3", align="R")
        pdf.set_text_color(*TEXT)

    def section_bar(title, y):
        pdf.set_fill_color(*NAV); pdf.rect(10, y, 190, 6, 'F')
        pdf.set_font("Helvetica", "B", 7.5); pdf.set_text_color(*WHT)
        pdf.set_xy(12, y + 0.8); pdf.cell(186, 4.5, safe(title))
        pdf.set_text_color(*TEXT); return y + 7

    def card(x, y, w, h):
        pdf.set_fill_color(*BG); pdf.set_draw_color(*LGREY); pdf.rect(x, y, w, h, 'FD')

    def divider(y):
        pdf.set_draw_color(*LGREY); pdf.line(10, y, 200, y)

    def kv(x, y, k, v, kw=30, vw=40, val_bold=False, val_color=None):
        pdf.set_font("Helvetica", "B", 7); pdf.set_text_color(*MUTED)
        pdf.set_xy(x, y); pdf.cell(kw, 4.5, safe(f"{k}:"), ln=False)
        pdf.set_font("Helvetica", "B" if val_bold else "", 8)
        pdf.set_text_color(*(val_color if val_color else TEXT))
        pdf.set_xy(x + kw, y); pdf.cell(vw, 4.5, safe(str(v))); pdf.set_text_color(*TEXT)

    def badge(x, y, text, color):
        tw = len(text) * 2.1 + 4
        pdf.set_fill_color(*color); pdf.set_draw_color(*color); pdf.rect(x, y, tw, 5, 'F')
        pdf.set_font("Helvetica", "B", 7); pdf.set_text_color(*WHT)
        pdf.set_xy(x, y); pdf.cell(tw, 5, safe(text), align="C"); pdf.set_text_color(*TEXT)

    # PAGE 1
    draw_header("AI Brain Tumor Analysis Report", f"File: {filename}",
                f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Sequence: {MRI_PARAMS['sequence']}")
    sev_color = (140,0,0) if severity=="Severe" else ((160,80,0) if severity=="Moderate" else (0,100,0))
    pdf.set_fill_color(*sev_color); pdf.rect(10, 15, 190, 8, 'F')
    pdf.set_font("Helvetica", "B", 7.5); pdf.set_text_color(*WHT)
    banner = (f" SEVERITY: {severity.upper()}  |  PREDICTION: {label.upper()}  |"
              f"  CONFIDENCE: {confidence:.2%}  |  GROWTH RISK: {risk_info['risk'].upper()} ")
    pdf.set_xy(10, 17); pdf.cell(190, 4, safe(banner), align="C"); pdf.set_text_color(*TEXT)

    y = 24; y = section_bar("ANALYSIS SUMMARY", y)
    ROW = 6; CARD_H = 6 * ROW + 4; card(10, y, 190, CARD_H)
    cols = [
        [(12,"Tumor Type",label.upper()), (12,"Confidence",f"{confidence:.2%}"),
         (12,"Uncertainty",cal_info['uncertainty']), (12,"Calibration",cal_info['cal_score']), (12,"Severity",severity)],
        [(76,"Tumor Area",f"{size_info['area_cm2']} cm2"), (76,"Diameter",f"{size_info['diameter_cm']} cm"),
         (76,"Est. Volume",f"{size_info['volume_cm3']} cm3"), (76,"Brain Coverage",f"{size_info['tumor_percent']}%"),
         (76,"Bounding Box",(f"{size_info['bbox']['width_cm']}x{size_info['bbox']['height_cm']} cm") if size_info['bbox'] else "N/A")],
        [(140,"Laterality",mass_info['laterality']), (140,"Midline Shift",f"{mass_info['shift_mm']} mm"),
         (140,"Compression",mass_info['compression']), (140,"Sulcal Eff.",mass_info['sulcal']),
         (140,"Aggressiveness",f"{risk_info['score']:.3f} / 1.0")],
    ]
    for col in cols:
        for i, (cx, k, v) in enumerate(col): kv(cx, y + 2 + i * ROW, k, v, kw=30, vw=32)
    y += CARD_H + 2

    y = section_bar("VISUAL ANALYSIS", y)
    tmp = "/tmp/report_imgs"; os.makedirs(tmp, exist_ok=True)
    def sv(arr, name, bgr=True):
        p = f"{tmp}/{name}.jpg"
        if bgr: cv2.imwrite(p, arr)
        else:   plt.imsave(p, arr, cmap="jet")
        return p
    paths = [sv(orig,"orig"), sv(mask_overlay,"mask"), sv(heatmap,"heatmap",bgr=False), sv(gradcam_overlay,"gcam")]
    lbls  = ["Original MRI", "Segmentation", "GradCAM Heatmap", "GradCAM Overlay"]
    iw, ih = 44, 39; gap = (190 - 4*iw) / 5; card(10, y, 190, ih+10)
    for i, (p, l) in enumerate(zip(paths, lbls)):
        x = 10 + gap + i*(iw+gap); pdf.image(p, x=x, y=y+2, w=iw, h=ih)
        pdf.set_font("Helvetica","B",6.5); pdf.set_text_color(*MUTED)
        pdf.set_xy(x, y+ih+3); pdf.cell(iw, 3.5, safe(l), align="C")
    pdf.set_text_color(*TEXT); y += ih + 13

    y = section_bar("SHAPE ANALYSIS   |   MASS EFFECT   |   RISK SCORE", y)
    SMR_H = 30; card(10, y, 190, SMR_H); RH = 5.5
    pdf.set_draw_color(*LGREY)
    pdf.line(74, y+2, 74, y+SMR_H-2); pdf.line(138, y+2, 138, y+SMR_H-2)
    if shape_info:
        kv(12,y+2,     "Irregularity",str(shape_info['irregularity']),kw=24,vw=20)
        kv(12,y+2+RH,  "Compactness", str(shape_info['compactness']), kw=24,vw=20)
        kv(12,y+2+RH*2,"Convexity",   str(shape_info['convexity']),   kw=24,vw=20)
        kv(12,y+2+RH*3,"Border",      shape_info['border_def'],        kw=24,vw=20)
        kv(12,y+2+RH*4,"Roughness",   shape_info['roughness'],         kw=24,vw=20)
    kv(78,y+2,     "Laterality", mass_info['laterality'],       kw=26,vw=26)
    kv(78,y+2+RH,  "Shift",      f"{mass_info['shift_mm']} mm", kw=26,vw=26)
    kv(78,y+2+RH*2,"Compression",mass_info['compression'],      kw=26,vw=26)
    kv(78,y+2+RH*3,"Sulcal",     mass_info['sulcal'],           kw=26,vw=26)
    kv(142,y+2,     "Aggress. Score",f"{risk_info['score']:.3f} / 1.0",kw=28,vw=22,val_bold=True,val_color=SC)
    kv(142,y+2+RH,  "Growth Risk",   risk_info['risk'],                kw=28,vw=22,val_bold=True,val_color=SC)
    kv(142,y+2+RH*2,"Progression",   risk_info['progression_risk'],    kw=28,vw=22)
    kv(142,y+2+RH*3,"Uncertainty",   cal_info['uncertainty'],          kw=28,vw=22)
    y += SMR_H + 2

    if rano:
        y = section_bar("RANO CRITERIA ASSESSMENT", y); RANO_H = 24; card(10, y, 190, RANO_H)
        kv(12,y+3, "Size Category",rano['size_cat'],   kw=28,vw=28)
        kv(12,y+11,"Enhancement",  rano['enhancement'],kw=28,vw=28)
        kv(80,y+3, "Necrosis",     rano['necrosis'],   kw=22,vw=44)
        pdf.set_xy(80,y+11); pdf.set_font("Helvetica","B",7); pdf.set_text_color(*MUTED)
        pdf.cell(22,4.5,"Grade:",ln=False)
        pdf.set_font("Helvetica","B",7); pdf.set_text_color(*SC)
        pdf.multi_cell(88,4.5,safe(rano['grade'])); pdf.set_text_color(*TEXT); y += RANO_H + 2

    y = section_bar("CLINICAL DECISION SUPPORT", y)
    n = len(clinical['steps']); mid = (n+1)//2; ch = mid*5.5+14; card(10,y,190,ch)
    pdf.set_xy(12,y+3); pdf.set_font("Helvetica","B",7.5); pdf.set_text_color(*MUTED)
    pdf.cell(30,5,"Urgency Level:",ln=False); badge(42,y+3,f"  {clinical['urgency'].upper()}  ",SC)
    for i, step in enumerate(clinical['steps']):
        col = 0 if i < mid else 1; row = i if i < mid else i - mid
        pdf.set_xy(14+col*95, y+11+row*5.5)
        pdf.set_font("Helvetica","",7.5); pdf.set_text_color(*TEXT)
        pdf.cell(90,4.5,safe(f"  >>  {step}"))
    draw_footer(1)

    # PAGE 2
    chart = generate_risk_chart(size_info, risk_info, shape_info, mass_info)
    pdf.add_page()
    draw_header("Risk Analytics Dashboard", f"File: {filename}",
                f"Prediction: {label.upper()}   |   Confidence: {confidence:.2%}   |   Severity: {severity}")
    pdf.set_xy(10,25); pdf.set_font("Helvetica","I",7.5); pdf.set_text_color(*MUTED)
    pdf.cell(190,5,safe("Quantitative breakdown of tumor characteristics derived from segmentation and classification models."))
    pdf.set_text_color(*TEXT)
    y2 = 32; card(10,y2,190,95); pdf.image(chart,x=12,y=y2+3,w=186,h=89); y2 += 99
    y2 = section_bar("KEY METRICS AT A GLANCE",y2); STRIP_H=24; card(10,y2,190,STRIP_H)
    metric_items=[("Tumor Area",f"{size_info['area_cm2']} cm2"),("Diameter",f"{size_info['diameter_cm']} cm"),
                  ("Volume",f"{size_info['volume_cm3']} cm3"),("Brain Cov.",f"{size_info['tumor_percent']}%"),
                  ("Midline Shift",f"{mass_info['shift_mm']} mm"),("Risk Score",f"{risk_info['score']:.3f} / 1.0")]
    col_w = 190/len(metric_items)
    for i,(mk,mv) in enumerate(metric_items):
        cx = 10+i*col_w
        if i>0: pdf.set_draw_color(*LGREY); pdf.line(cx,y2+3,cx,y2+STRIP_H-3)
        pdf.set_font("Helvetica","B",6.5); pdf.set_text_color(*MUTED)
        pdf.set_xy(cx,y2+4); pdf.cell(col_w,4,safe(mk),align="C")
        pdf.set_font("Helvetica","B",10); pdf.set_text_color(*NAV)
        pdf.set_xy(cx,y2+10); pdf.cell(col_w,7,safe(mv),align="C")
    pdf.set_text_color(*TEXT); y2 += STRIP_H+4
    if shape_info:
        y2=section_bar("SHAPE DETAIL",y2); SHAPE_H=28; card(10,y2,190,SHAPE_H)
        shape_items=[
            ("Irregularity",shape_info['irregularity'],                        "Higher = more irregular boundary"),
            ("Compactness", round(min(shape_info['compactness']/3.5,1.0),3),   "Normalised compactness score (0-1)"),
            ("Eccentricity",shape_info['eccentricity'],                         "Elongation of fitted ellipse"),
            ("Convexity",   shape_info['convexity'],                            "How convex the tumor contour is"),
            ("Border",      shape_info['border_def'],                           "Border definition quality"),
            ("Roughness",   shape_info['roughness'],                            "Surface texture assessment")]
        sh_col_w=190/3
        for i,(sk,sv2,desc) in enumerate(shape_items):
            col_i=i%3; row_i=i//3; cx2=10+col_i*sh_col_w+3; cy2=y2+3+row_i*11
            pdf.set_font("Helvetica","B",7); pdf.set_text_color(*MUTED)
            pdf.set_xy(cx2,cy2); pdf.cell(sh_col_w-3,4.5,safe(f"{sk}:"),ln=False)
            pdf.set_font("Helvetica","B",8); pdf.set_text_color(*NAV)
            pdf.set_xy(cx2+26,cy2); pdf.cell(30,4.5,safe(str(sv2)),ln=False)
            pdf.set_font("Helvetica","I",6); pdf.set_text_color(*MUTED)
            pdf.set_xy(cx2,cy2+5); pdf.cell(sh_col_w-3,4,safe(desc))
        pdf.set_text_color(*TEXT); y2+=SHAPE_H+4
    y2=max(y2,245)
    pdf.set_fill_color(255,248,230); pdf.set_draw_color(230,180,80); pdf.rect(10,y2,190,14,'FD')
    pdf.set_font("Helvetica","B",7); pdf.set_text_color(160,100,0)
    pdf.set_xy(13,y2+2.5); pdf.cell(10,4.5,"(!)",ln=False)
    pdf.set_font("Helvetica","",7); pdf.set_xy(20,y2+2.5)
    pdf.multi_cell(177,4.5,
        "IMPORTANT: This AI-generated analysis is intended for screening and research purposes only. "
        "All findings must be reviewed and validated by a qualified radiologist or neurosurgeon before "
        "any clinical decisions are made. Histopathological confirmation is required for definitive diagnosis.")
    pdf.set_text_color(*TEXT); draw_footer(2)

    # PAGE 3
    pdf.add_page()
    draw_header("AI Generated Radiology Report", f"File: {filename}",
                "Note: AI-generated imaging findings. Histopathological confirmation is required for definitive diagnosis.")
    y3=25; divider(y3); y3+=3
    for line in llm_report.split("\n"):
        line=safe(line.strip())
        if not line: y3+=2; continue
        if y3>275: break
        is_section=any(line.startswith(h) for h in ["1.","2.","3.","4.","5.","6.","7.","8.","9."])
        if is_section:
            y3+=2; pdf.set_fill_color(*NAV); pdf.rect(10,y3,3.5,6.5,'F')
            pdf.set_fill_color(230,235,250); pdf.rect(14,y3,186,6.5,'F')
            pdf.set_font("Helvetica","B",8.5); pdf.set_text_color(*NAV)
            pdf.set_xy(16,y3+0.8); pdf.cell(183,5.5,safe(f" {line}"))
            pdf.set_text_color(*TEXT); y3+=9
        else:
            pdf.set_font("Helvetica","",8); pdf.set_text_color(50,55,65)
            pdf.set_xy(14,y3); pdf.multi_cell(184,4.8,line); y3=pdf.get_y()+1
    draw_footer(3)

    safe_name = os.path.splitext(filename)[0]
    ts  = datetime.now().strftime('%Y%m%d%H%M%S')
    out = os.path.join(REPORT_DIR, f"{safe_name}_{ts}_mri_report.pdf")
    pdf.output(out)
    return out

# ════════════════════════════════════════════════════
# PATIENT HISTORY
# ════════════════════════════════════════════════════
def load_history():
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE) as f: return json.load(f)
    return []

def save_to_history(record):
    history = load_history(); history.insert(0, record)
    with open(HISTORY_FILE, "w") as f: json.dump(history[:50], f, indent=2)

# ════════════════════════════════════════════════════
# SIDEBAR
# ════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("## 🧠 NeuroScan AI")
    st.caption("Brain Tumor MRI Analysis System")
    st.markdown("---")
    page = st.radio("Navigate", ["🏥 Dashboard", "📋 Patient History", "ℹ️ Model Info"],
                    label_visibility="collapsed")
    st.markdown("---")
    st.markdown("### Models")
    st.markdown("""
    <div style='font-size:12px;line-height:2'>
    <span style='color:#4dc86f'>✓</span> EfficientNetV2-S<br>
    <span style='color:#4dc86f'>✓</span> U-Net Segmentation<br>
    <span style='color:#4dc86f'>✓</span> Grad-CAM<br>
    <span style='color:#4dc86f'>✓</span> Groq LLM (Llama-4)
    </div>""", unsafe_allow_html=True)
    st.markdown("---")
    st.caption("⚠️ For research & screening only. Not for clinical diagnosis.")

# ════════════════════════════════════════════════════
# PAGE: DASHBOARD
# ════════════════════════════════════════════════════
if page == "🏥 Dashboard":
    st.title("Doctor Dashboard")
    st.caption("Upload an MRI scan to run the full AI analysis pipeline.")
    st.markdown("---")

    col_left, col_right = st.columns([1, 1.7], gap="large")

    with col_left:
        st.subheader("📤 Upload MRI Scan")
        uploaded = st.file_uploader("Drop MRI here", type=["png","jpg","jpeg","bmp"],
                                     label_visibility="collapsed")
        if uploaded:
            st.image(uploaded, caption="Uploaded MRI", use_container_width=True)

        run_btn = st.button("▶  Run Full Analysis", disabled=uploaded is None)

        if uploaded and run_btn:
            suffix   = "." + uploaded.name.split(".")[-1]
            tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
            tmp_file.write(uploaded.getvalue()); tmp_file.close()
            tmp_path = tmp_file.name

            # ── STEP 1: Classification (always runs) ──
            with st.spinner("Step 1/5 — Classifying tumor..."):
                class_model, seg_model, base_model, head_layers = load_models()
                orig       = cv2.resize(cv2.imread(tmp_path), (IMG_SIZE, IMG_SIZE))
                img_class  = load_class_image(tmp_path)
                img_tensor = tf.convert_to_tensor(img_class)
                preds      = class_model(img_tensor, training=False)[0].numpy()
                class_id   = int(np.argmax(preds))
                label      = CLASS_NAMES[class_id]
                confidence = float(preds[class_id])

            if label == "no_tumor":
                # ── NO TUMOR PATH: skip steps 2-4, just generate normal report ──
                st.info("🟢 No tumor detected — skipping segmentation and metrics.")
                with st.spinner("Generating normal radiology report..."):
                    llm_report = generate_normal_llm_report(tmp_path, confidence)
                    pdf_path   = save_normal_pdf_report(uploaded.name, tmp_path,
                                                         confidence, llm_report, orig)
                st.session_state["result"] = {
                    "label": label, "confidence": confidence, "severity": "None",
                    "filename": uploaded.name, "llm_report": llm_report, "pdf_path": pdf_path,
                    "orig": orig, "no_tumor": True,
                    "size_info": None, "shape_info": None, "mass_info": None,
                    "risk_info": {"score":0.0,"risk":"None","progression_risk":"0%"},
                    "cal_info": compute_confidence_calibration(confidence),
                    "clinical": {"steps":["Routine follow-up in 12 months","No immediate action required"],"urgency":"Low"},
                    "rano": None, "mask_overlay": None, "hmap_r": None, "gcam_ov": None,
                }
                save_to_history({
                    "id":f"#MRI-{len(load_history())+1:03d}","filename":uploaded.name,
                    "label":"No Tumor","confidence":f"{confidence*100:.1f}%",
                    "severity":"None","area_cm2":"N/A",
                    "risk":"None","date":datetime.now().strftime("%b %d, %Y %H:%M"),
                })
                st.success("✅ Analysis complete — Normal MRI!")

            else:
                # ── TUMOR PATH: run full pipeline ──
                with st.spinner("Step 2/5 — Segmenting tumor region..."):
                    gray   = cv2.resize(cv2.imread(tmp_path, cv2.IMREAD_GRAYSCALE), (SEG_SIZE, SEG_SIZE))
                    seg_in = np.expand_dims(gray / 255.0, (0, -1))
                    mask   = (seg_model(seg_in, training=False)[0].numpy() > 0.5).astype(np.uint8)
                    mask   = cv2.resize(mask, (IMG_SIZE, IMG_SIZE))

                with st.spinner("Step 3/5 — Generating Grad-CAM heatmap..."):
                    heatmap = get_gradcam_heatmap(img_tensor, base_model, head_layers)

                with st.spinner("Step 4/5 — Computing metrics..."):
                    size_info  = estimate_tumor_size(mask)
                    shape_info = analyze_tumor_shape(mask)
                    mass_info  = detect_mass_effect(mask)
                    risk_info  = compute_risk_score(label, confidence, size_info, shape_info, mass_info)
                    cal_info   = compute_confidence_calibration(confidence)
                    severity   = get_severity(label, confidence, size_info['tumor_percent'])
                    rec        = get_recommendation(label, severity)
                    clinical   = get_clinical_decision(label, severity, mass_info)
                    rano       = get_rano_assessment(label, size_info, shape_info)
                    mask_vis     = np.uint8(mask * 255)
                    mask_color   = cv2.applyColorMap(mask_vis, cv2.COLORMAP_HOT)
                    mask_overlay = cv2.addWeighted(orig, 0.7, mask_color, 0.3, 0)
                    if size_info['bbox']:
                        b = size_info['bbox']
                        cv2.rectangle(mask_overlay,(b['x'],b['y']),(b['x']+b['w'],b['y']+b['h']),(0,255,0),2)
                        cv2.putText(mask_overlay,f"{size_info['diameter_cm']}cm",
                                    (b['x'],b['y']-8),cv2.FONT_HERSHEY_SIMPLEX,0.6,(0,255,0),2)
                    hmap_r  = cv2.resize(heatmap, (IMG_SIZE, IMG_SIZE))
                    hmap_c  = cv2.applyColorMap(np.uint8(255*hmap_r), cv2.COLORMAP_JET)
                    gcam_ov = cv2.addWeighted(orig, 0.6, hmap_c, 0.4, 0)

                with st.spinner("Step 5/5 — Generating LLM radiology report..."):
                    llm_report = generate_llm_report(tmp_path, label, confidence, size_info,
                                                      shape_info, mass_info, risk_info, severity, rec, rano)
                    pdf_path   = save_pdf_report(uploaded.name, tmp_path, label, confidence,
                                                  size_info, shape_info, mass_info, risk_info, cal_info,
                                                  severity, rec, llm_report, clinical, rano,
                                                  orig, mask_overlay, hmap_r, gcam_ov)

                st.session_state["result"] = {
                    "label":label,"confidence":confidence,"severity":severity,"filename":uploaded.name,
                    "size_info":size_info,"shape_info":shape_info,"mass_info":mass_info,
                    "risk_info":risk_info,"cal_info":cal_info,"clinical":clinical,"rano":rano,
                    "llm_report":llm_report,"pdf_path":pdf_path,"no_tumor":False,
                    "orig":orig,"mask_overlay":mask_overlay,"hmap_r":hmap_r,"gcam_ov":gcam_ov,
                }
                save_to_history({
                    "id":f"#MRI-{len(load_history())+1:03d}","filename":uploaded.name,
                    "label":label.capitalize(),"confidence":f"{confidence*100:.1f}%",
                    "severity":severity,"area_cm2":size_info['area_cm2'],
                    "risk":risk_info['risk'],"date":datetime.now().strftime("%b %d, %Y %H:%M"),
                })
                st.success("✅ Analysis complete!")

        if "result" in st.session_state:
            res = st.session_state["result"]
            st.markdown("---")
            st.subheader("🔬 Detection Result")
            sev     = res['severity']
            tag_cls = "tag-red" if sev=="Severe" else ("tag-amber" if sev=="Moderate" else "tag-green")
            icon    = "🔴" if sev=="Severe" else ("🟡" if sev=="Moderate" else "🟢")
            st.markdown(f"""
            <div style='background:#111318;border:1px solid #1e2330;border-radius:10px;
                        padding:14px 16px;margin-bottom:12px;display:flex;align-items:center;gap:12px'>
              <div style='font-size:28px'>{icon}</div>
              <div>
                <div style='font-size:18px;font-weight:700;color:#e2e5ed'>{res['label'].replace("_"," ").capitalize()}</div>
                <div style='font-size:12px;color:#7a8299'>Classified by EfficientNetV2-S</div>
              </div>
              <div style='margin-left:auto'><span class='{tag_cls}'>{sev.upper()}</span></div>
            </div>""", unsafe_allow_html=True)

            if res.get("no_tumor"):
                # Clean no-tumor metrics
                st.metric("Confidence", f"{res['confidence']*100:.1f}%")
                st.success("✅ No intracranial mass or tumor identified. Brain appears normal.")
            else:
                c1, c2 = st.columns(2)
                with c1:
                    st.metric("Confidence",  f"{res['confidence']*100:.1f}%")
                    st.metric("Tumor Area",  f"{res['size_info']['area_cm2']} cm²")
                    st.metric("Risk Score",  f"{res['risk_info']['score']:.3f} / 1.0")
                with c2:
                    st.metric("Diameter",    f"{res['size_info']['diameter_cm']} cm")
                    st.metric("Volume",      f"{res['size_info']['volume_cm3']} cm³")
                    st.metric("Growth Risk", res['risk_info']['risk'])

            st.markdown("---")
            st.subheader("📋 Clinical Decision")
            urg = res['clinical']['urgency']
            urg_color = "#e8604a" if urg=="Critical" else ("#d4a843" if urg=="High" else "#4dc86f")
            st.markdown(f"**Urgency:** <span style='color:{urg_color};font-weight:700'>{urg.upper()}</span>",
                        unsafe_allow_html=True)
            for step in res['clinical']['steps']:
                st.markdown(f"→ {step}")

            st.markdown("---")
            st.subheader("📄 PDF Report")
            if os.path.exists(res.get("pdf_path","")):
                with open(res["pdf_path"],"rb") as f:
                    st.download_button(
                        label="⬇  Download Full PDF Report", data=f,
                        file_name=f"neuroscan_{res['filename']}_{datetime.now().strftime('%Y%m%d%H%M')}.pdf",
                        mime="application/pdf", use_container_width=True
                    )

    with col_right:
        if "result" in st.session_state:
            res = st.session_state["result"]

            if res.get("no_tumor"):
                # ── NO TUMOR: show only original MRI + report ──
                st.subheader("📊 Scan")
                st.image(cv2.cvtColor(res['orig'], cv2.COLOR_BGR2RGB),
                         caption="Original MRI — No abnormality detected", use_container_width=True)
            else:
                # ── TUMOR: show full 4-image grid ──
                st.subheader("📊 Scan Visualization")
                c1, c2 = st.columns(2)
                with c1:
                    st.image(cv2.cvtColor(res['orig'],cv2.COLOR_BGR2RGB),
                             caption="Original MRI", use_container_width=True)
                    st.image(res['hmap_r'], caption="Grad-CAM Heatmap",
                             use_container_width=True, clamp=True)
                with c2:
                    st.image(cv2.cvtColor(res['mask_overlay'],cv2.COLOR_BGR2RGB),
                             caption=f"Segmentation | D: {res['size_info']['diameter_cm']} cm",
                             use_container_width=True)
                    st.image(cv2.cvtColor(res['gcam_ov'],cv2.COLOR_BGR2RGB),
                             caption="Grad-CAM Overlay", use_container_width=True)

            st.markdown("---")
            st.subheader("📝 AI Radiology Report")
            with st.expander("View Full Report", expanded=True):
                for line in res['llm_report'].split('\n'):
                    line = line.strip()
                    if not line: continue
                    if any(line.startswith(h) for h in ["1.","2.","3.","4.","5.","6."]):
                        st.markdown(f"**{line}**")
                    else:
                        st.write(line)

            if res.get('rano'):
                st.markdown("---")
                st.subheader("🏥 RANO Assessment")
                c1, c2 = st.columns(2)
                with c1:
                    st.metric("Size Category", res['rano']['size_cat'])
                    st.metric("Enhancement",   res['rano']['enhancement'])
                with c2:
                    st.metric("Necrosis",      res['rano']['necrosis'])
                st.caption(res['rano']['grade'])
        else:
            st.info("Upload an MRI scan on the left and click **Run Full Analysis** to see results here.")

# ════════════════════════════════════════════════════
# PAGE: PATIENT HISTORY
# ════════════════════════════════════════════════════
elif page == "📋 Patient History":
    st.title("Patient History")
    st.caption("All cases analyzed in this session and previous sessions.")
    st.markdown("---")
    history = load_history()
    if not history:
        st.info("No cases analyzed yet. Go to the Dashboard to analyze an MRI scan.")
    else:
        import pandas as pd
        df = pd.DataFrame(history)
        df = df.rename(columns={
            "id":"Case ID","filename":"File","label":"Tumor Type",
            "confidence":"Confidence","severity":"Severity",
            "area_cm2":"Area (cm²)","risk":"Risk","date":"Date"
        })
        st.dataframe(df, use_container_width=True, hide_index=True)
        st.markdown("---")
        c1, c2, c3 = st.columns(3)
        with c1: st.metric("Total Cases",    len(history))
        with c2: st.metric("Severe Cases",   sum(1 for h in history if h.get("severity")=="Severe"))
        with c3: st.metric("Tumor Detected", sum(1 for h in history if h.get("label","").lower()!="no_tumor"))

# ════════════════════════════════════════════════════
# PAGE: MODEL INFO
# ════════════════════════════════════════════════════
elif page == "ℹ️ Model Info":
    st.title("Model Information")
    st.markdown("---")
    c1, c2, c3 = st.columns(3)
    with c1:
        st.subheader("Classification")
        st.metric("Architecture", "EfficientNetV2-S")
        st.metric("Classes",      "4")
        st.metric("Input Size",   f"{IMG_SIZE}×{IMG_SIZE}")
        st.caption("Classifies: Glioma, Meningioma, Pituitary, No Tumor")
    with c2:
        st.subheader("Segmentation")
        st.metric("Architecture", "U-Net (LGG)")
        st.metric("Input Size",   f"{SEG_SIZE}×{SEG_SIZE}")
        st.metric("Output",       "Binary Mask")
        st.caption("Segments tumor region pixel-by-pixel")
    with c3:
        st.subheader("Explainability & Report")
        st.metric("Heatmap", "Grad-CAM")
        st.metric("LLM",     "Llama-4 Scout (Groq)")
        st.metric("Report",  "3-page PDF")
        st.caption("Full radiology report with risk analytics")
    st.markdown("---")
    st.subheader("MRI Parameters")
    for k, v in MRI_PARAMS.items():
        st.write(f"**{k.replace('_',' ').title()}:** {v}")
    st.markdown("---")
    st.warning("⚠️ This system is for screening and research purposes only. "
               "All AI outputs must be reviewed by a qualified radiologist or neurosurgeon "
               "before any clinical decisions are made.")

import requests, subprocess

# Kill any stuck tunnels
try:
    tunnels = requests.get("http://localhost:4040/api/tunnels").json()
    for t in tunnels.get("tunnels", []):
        requests.delete(f"http://localhost:4040/api/tunnels/{t['name']}")
        print(f"Deleted: {t['name']}")
except:
    print("No existing tunnels")

subprocess.run(["pkill", "-f", "ngrok"], capture_output=True)
subprocess.run(["pkill", "-f", "streamlit"], capture_output=True)
print("✅ Cleaned up")

from pyngrok import ngrok
import subprocess, time, requests

# Start Streamlit
proc = subprocess.Popen([
    "streamlit", "run", "app.py",
    "--server.port", "8501",
    "--server.headless", "true"
])

# Wait until up
print("Waiting for Streamlit...")
for i in range(30):
    try:
        if requests.get("http://localhost:8501").status_code == 200:
            print("✅ Streamlit is up!")
            break
    except:
        pass
    time.sleep(2)
    print(f"  ...{i*2}s")

# Connect ngrok
ngrok.set_auth_token("358HfFSjXSmlojBiorl4mNse6xs_MJS8wgAkf3qAxFhZUVnY")
url = ngrok.connect(8501)
print(f"\n🚀 Live at: {url}")

"""#one error to be correct is when classification is done and the resulte are  giveing an output of no tumor it goes and guess it as tumeo"""