# -*- coding: utf-8 -*-
"""segmentaion_brain_seg_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KI-ZKKZHmNXWyoIjVJp1DldUqkwfirER

CELL 1 — MOUNT DRIVE
"""

from google.colab import drive
drive.mount("/content/drive")

"""CELL 2 — IMPORTS"""

import os
import re
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from glob import glob
from sklearn.metrics import confusion_matrix
from scipy.ndimage import map_coordinates, gaussian_filter

"""CELL 3 — PATHS"""

BASE="/content/drive/MyDrive/Project work/Dataset/lgg-mri-segmentation/lgg_structured"

MODEL_DIR="/content/drive/MyDrive/Project work/models/Segmentation"
os.makedirs(MODEL_DIR,exist_ok=True)

TRAIN_IMG=os.path.join(BASE,"train/images")
TRAIN_MASK=os.path.join(BASE,"train/masks")

VAL_IMG=os.path.join(BASE,"val/images")
VAL_MASK=os.path.join(BASE,"val/masks")

TEST_IMG=os.path.join(BASE,"test/images")
TEST_MASK=os.path.join(BASE,"test/masks")

CKPT="/content/best.h5"
SAVE_PATH=os.path.join(MODEL_DIR,"attention_resunet___.keras")

for name,p in [
("train_img",TRAIN_IMG),
("train_mask",TRAIN_MASK),
("val_img",VAL_IMG),
("val_mask",VAL_MASK),
("test_img",TEST_IMG),
("test_mask",TEST_MASK)
]:
    print(name,os.path.exists(p))

"""CELL 4 — CONFIG"""

IMG_SIZE=256
BATCH_SIZE=8
EPOCHS=80
SEED=42
AUTOTUNE=tf.data.AUTOTUNE

"""CELL 5 — DATA LOADING"""

def nsort(p):
    return [int(n) for n in re.findall(r"\d+",os.path.basename(p))]

train_imgs=sorted(glob(os.path.join(TRAIN_IMG,"*")),key=nsort)
train_masks=sorted(glob(os.path.join(TRAIN_MASK,"*")),key=nsort)

val_imgs=sorted(glob(os.path.join(VAL_IMG,"*")),key=nsort)
val_masks=sorted(glob(os.path.join(VAL_MASK,"*")),key=nsort)

test_imgs=sorted(glob(os.path.join(TEST_IMG,"*")),key=nsort)
test_masks=sorted(glob(os.path.join(TEST_MASK,"*")),key=nsort)

print("Train:",len(train_imgs))
print("Val:",len(val_imgs))
print("Test:",len(test_imgs))

assert len(train_imgs)==len(train_masks)
assert len(val_imgs)==len(val_masks)

"""CELL 6 — FILTER EMPTY MASKS"""

def has_tumor(mask_path):

    m=cv2.imread(mask_path,cv2.IMREAD_GRAYSCALE)

    return m is not None and m.max()>0


train_pairs=[(i,m) for i,m in zip(train_imgs,train_masks) if has_tumor(m)]
val_pairs=[(i,m) for i,m in zip(val_imgs,val_masks) if has_tumor(m)]

train_imgs_f,train_masks_f=map(list,zip(*train_pairs))
val_imgs_f,val_masks_f=map(list,zip(*val_pairs))

print("Filtered Train:",len(train_imgs_f))
print("Filtered Val:",len(val_imgs_f))

"""CELL 7 — PREPROCESSING"""

def load_image(path):

    img=cv2.imread(path.numpy().decode(),cv2.IMREAD_GRAYSCALE)

    if img is None:
        return np.zeros((IMG_SIZE,IMG_SIZE,1),np.float32)

    img=cv2.resize(img,(IMG_SIZE,IMG_SIZE)).astype(np.float32)/255.0

    clahe=cv2.createCLAHE(clipLimit=2.0,tileGridSize=(8,8))
    img=clahe.apply((img*255).astype(np.uint8))

    img=img.astype(np.float32)/255.0

    return np.expand_dims(img,-1)


def load_mask(path):

    m=cv2.imread(path.numpy().decode(),cv2.IMREAD_GRAYSCALE)

    if m is None:
        return np.zeros((IMG_SIZE,IMG_SIZE,1),np.float32)

    m=cv2.resize(m,(IMG_SIZE,IMG_SIZE),interpolation=cv2.INTER_NEAREST)
    m=(m>127).astype(np.float32)

    return np.expand_dims(m,-1)


def parse(img_path,mask_path):

    img=tf.py_function(load_image,[img_path],tf.float32)
    mask=tf.py_function(load_mask,[mask_path],tf.float32)

    img.set_shape([IMG_SIZE,IMG_SIZE,1])
    mask.set_shape([IMG_SIZE,IMG_SIZE,1])

    return img,mask

"""CELL 8 — AUGMENTATION"""

def augment(img,mask):

    if tf.random.uniform(())>0.5:
        img=tf.image.flip_left_right(img)
        mask=tf.image.flip_left_right(mask)

    if tf.random.uniform(())>0.5:
        img=tf.image.flip_up_down(img)
        mask=tf.image.flip_up_down(mask)

    k=tf.random.uniform([],0,4,dtype=tf.int32)
    img=tf.image.rot90(img,k)
    mask=tf.image.rot90(mask,k)

    mask=tf.cast(mask>0.5,tf.float32)

    return img,mask


def to_dict(img,mask):
    return img, mask

"""CELL 9 — DATA PIPELINE"""

train_ds=(
tf.data.Dataset.from_tensor_slices((train_imgs_f,train_masks_f))
.shuffle(len(train_imgs_f),seed=SEED)
.map(parse,num_parallel_calls=AUTOTUNE)
.map(augment,num_parallel_calls=AUTOTUNE)
.map(to_dict,num_parallel_calls=AUTOTUNE)
.batch(BATCH_SIZE)
.prefetch(AUTOTUNE)
)

val_ds=(
tf.data.Dataset.from_tensor_slices((val_imgs_f,val_masks_f))
.map(parse,num_parallel_calls=AUTOTUNE)
.map(to_dict,num_parallel_calls=AUTOTUNE)
.batch(BATCH_SIZE)
.prefetch(AUTOTUNE)
)

print("datasets ready")

"""CELL 10 — LOSS & METRICS"""

def dice_coef(y_true,y_pred,smooth=1):

    y_true=tf.reshape(tf.cast(y_true,tf.float32),[-1])
    y_pred=tf.reshape(tf.cast(y_pred,tf.float32),[-1])

    inter=tf.reduce_sum(y_true*y_pred)

    return (2*inter+smooth)/(tf.reduce_sum(y_true)+tf.reduce_sum(y_pred)+smooth)


def combined_loss(y_true,y_pred):

    bce=tf.reduce_mean(tf.keras.losses.binary_crossentropy(y_true,y_pred))

    inter=tf.reduce_sum(y_true*y_pred)
    dice=(2*inter+1)/(tf.reduce_sum(y_true)+tf.reduce_sum(y_pred)+1)

    return bce+(1-dice)

"""CELL 11 — MODEL BLOCKS"""

def conv_block(x,f):

    x=tf.keras.layers.Conv2D(f,3,padding="same")(x)
    x=tf.keras.layers.BatchNormalization()(x)
    x=tf.keras.layers.Activation("relu")(x)

    x=tf.keras.layers.Conv2D(f,3,padding="same")(x)
    x=tf.keras.layers.BatchNormalization()(x)
    x=tf.keras.layers.Activation("relu")(x)

    return x


def res_block(inp,f):

    x=conv_block(inp,f)

    r=tf.keras.layers.Conv2D(f,1,padding="same")(inp)

    return tf.keras.layers.Add()([x,r])

"""CELL 12 — BUILD MODEL"""

def build_model(size):

    inp=tf.keras.Input((size,size,1))

    e1=res_block(inp,64)
    p1=tf.keras.layers.MaxPooling2D()(e1)

    e2=res_block(p1,128)
    p2=tf.keras.layers.MaxPooling2D()(e2)

    e3=res_block(p2,256)
    p3=tf.keras.layers.MaxPooling2D()(e3)

    b=conv_block(p3,512)

    u1=tf.keras.layers.Conv2DTranspose(256,2,strides=2,padding="same")(b)
    d1=conv_block(tf.keras.layers.Concatenate()([u1,e3]),256)

    u2=tf.keras.layers.Conv2DTranspose(128,2,strides=2,padding="same")(d1)
    d2=conv_block(tf.keras.layers.Concatenate()([u2,e2]),128)

    u3=tf.keras.layers.Conv2DTranspose(64,2,strides=2,padding="same")(d2)
    d3=conv_block(tf.keras.layers.Concatenate()([u3,e1]),64)

    out=tf.keras.layers.Conv2D(1,1,activation="sigmoid")(d3)

    return tf.keras.Model(inp,out)

model=build_model(IMG_SIZE)
model.summary()

"""CELL 13 — COMPILE"""

model.compile(
optimizer=tf.keras.optimizers.Adam(1e-4),
loss=combined_loss,
metrics=[dice_coef]
)

"""CELL 14 — CALLBACKS"""

callbacks=[

tf.keras.callbacks.ModelCheckpoint(
CKPT,
monitor="val_dice_coef",
mode="max",
save_best_only=True
),

tf.keras.callbacks.EarlyStopping(
monitor="val_dice_coef",
mode="max",
patience=15,
restore_best_weights=True
)

]

"""CELL 15 — TRAIN"""

history=model.fit(
train_ds,
validation_data=val_ds,
epochs=EPOCHS,
callbacks=callbacks
)

"""CELL 16 — GRAPH"""

plt.plot(history.history["dice_coef"])
plt.plot(history.history["val_dice_coef"])
plt.title("Dice Score")
plt.legend(["train","val"])
plt.show()

"""CELL 17 — TEST DATASET"""

test_ds=(
tf.data.Dataset.from_tensor_slices((test_imgs,test_masks))
.map(parse)
.batch(BATCH_SIZE)
)

"""CELL 18 — EVALUATION"""

results=model.evaluate(test_ds)

print("Test Dice:",results[1])

"""CELL 19 — SAVE MODEL"""

model.save(SAVE_PATH)

print("Model saved:",SAVE_PATH)