# -*- coding: utf-8 -*-
"""image_loader.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zn0gu5Gbz93LvQNdb0CH72Kqrmkg8-U6
"""

import os
import cv2
import numpy as np
import tensorflow as tf
from glob import glob

IMG_SIZE = 256
BATCH = 16
EPOCHS = 30

train_img = sorted(glob("dataset/train/images/*"))
train_mask = sorted(glob("dataset/train/masks/*"))

val_img = sorted(glob("dataset/val/images/*"))
val_mask = sorted(glob("dataset/val/masks/*"))

def load_img(path):
    img = cv2.imread(path.decode(),0)
    img = cv2.resize(img,(IMG_SIZE,IMG_SIZE))
    img = img/255.0
    img = np.expand_dims(img,-1)
    return img.astype(np.float32)

def load_mask(path):
    mask = cv2.imread(path.decode(),0)
    mask = cv2.resize(mask,(IMG_SIZE,IMG_SIZE))
    mask = (mask>127).astype(np.float32)
    mask = np.expand_dims(mask,-1)
    return mask

def parse(x,y):
    x=tf.numpy_function(load_img,[x],tf.float32)
    y=tf.numpy_function(load_mask,[y],tf.float32)
    x.set_shape([IMG_SIZE,IMG_SIZE,1])
    y.set_shape([IMG_SIZE,IMG_SIZE,1])
    return x,y

def dataset(img,mask):
    ds=tf.data.Dataset.from_tensor_slices((img,mask))
    ds=ds.map(parse,num_parallel_calls=tf.data.AUTOTUNE)
    ds=ds.batch(BATCH).prefetch(tf.data.AUTOTUNE)
    return ds

train_ds=dataset(train_img,train_mask)
val_ds=dataset(val_img,val_mask)

def conv(x,f):
    x=tf.keras.layers.Conv2D(f,3,padding="same",activation="relu")(x)
    x=tf.keras.layers.Conv2D(f,3,padding="same",activation="relu")(x)
    return x

inp=tf.keras.Input((IMG_SIZE,IMG_SIZE,1))

c1=conv(inp,64); p1=tf.keras.layers.MaxPool2D()(c1)
c2=conv(p1,128); p2=tf.keras.layers.MaxPool2D()(c2)
c3=conv(p2,256); p3=tf.keras.layers.MaxPool2D()(c3)
c4=conv(p3,512); p4=tf.keras.layers.MaxPool2D()(c4)

bn=conv(p4,1024)

u1=tf.keras.layers.Conv2DTranspose(512,2,2,padding="same")(bn)
u1=tf.concat([u1,c4],-1); c5=conv(u1,512)

u2=tf.keras.layers.Conv2DTranspose(256,2,2,padding="same")(c5)
u2=tf.concat([u2,c3],-1); c6=conv(u2,256)

u3=tf.keras.layers.Conv2DTranspose(128,2,2,padding="same")(c6)
u3=tf.concat([u3,c2],-1); c7=conv(u3,128)

u4=tf.keras.layers.Conv2DTranspose(64,2,2,padding="same")(c7)
u4=tf.concat([u4,c1],-1); c8=conv(u4,64)

out=tf.keras.layers.Conv2D(1,1,activation="sigmoid")(c8)

model=tf.keras.Model(inp,out)

def dice(y_true,y_pred):
    y_true=tf.keras.backend.flatten(y_true)
    y_pred=tf.keras.backend.flatten(y_pred)
    inter=tf.reduce_sum(y_true*y_pred)
    return (2*inter+1e-6)/(tf.reduce_sum(y_true)+tf.reduce_sum(y_pred)+1e-6)

def loss(y_true,y_pred):
    bce=tf.keras.losses.binary_crossentropy(y_true,y_pred)
    return bce+(1-dice(y_true,y_pred))

model.compile(optimizer="adam",loss=loss,metrics=[dice])

model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

model.save("models/segmentation_unet.keras")