# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zn0gu5Gbz93LvQNdb0CH72Kqrmkg8-U6
"""

import cv2
import numpy as np

IMG_SIZE = 256

def normalize_image(img):
    img = img.astype(np.float32)
    img = img / 255.0
    return img

def resize_image(img, size=IMG_SIZE):
    img = cv2.resize(img, (size, size))
    return img

def apply_clahe(img):
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    img = clahe.apply(img)
    return img

def preprocess_mri(img_path):
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    img = apply_clahe(img)
    img = resize_image(img)
    img = normalize_image(img)
    img = np.expand_dims(img, axis=-1)
    return img

def preprocess_mask(mask_path):
    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    mask = resize_image(mask)
    mask = (mask > 127).astype(np.float32)
    mask = np.expand_dims(mask, axis=-1)
    return mask