# -*- coding: utf-8 -*-
"""test-1-2-3-4-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10RgFdjitDdyhg9IYnqtCioTk3Dk2um0i
"""

!pip install groq fpdf2 pillow python-dotenv -q

from google.colab import drive
drive.mount('/content/drive')

import os, warnings, time, re
from pathlib import Path
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
warnings.filterwarnings('ignore')

import cv2, numpy as np, tensorflow as tf
tf.get_logger().setLevel('ERROR')
tf.autograph.set_verbosity(0)
import matplotlib.pyplot as plt
from tensorflow.keras.applications.efficientnet_v2 import preprocess_input as effv2_prep
from datetime import datetime
from dotenv import load_dotenv
from fpdf import FPDF
import base64
from groq import Groq

load_dotenv(Path.cwd() / ".env")

# ════════════════════════════════════════════════════
# CONFIG
# ════════════════════════════════════════════════════
BASE_DIR         = "/content/drive/MyDrive/Project work"
CLASS_MODEL_PATH = BASE_DIR + "/models/Classification/Tumor_v2s_clean.keras"
SEG_MODEL_PATH   = BASE_DIR + "/models/Segmentation/unet_lgg_segmentation_u-net.keras"
TEST_DIR         = BASE_DIR + "/Test Data"
REPORT_DIR       = "/content/sample_data"
os.makedirs(REPORT_DIR, exist_ok=True)
IMG_SIZE         = 384
SEG_SIZE         = 256
CLASS_NAMES      = ["glioma", "meningioma", "no_tumor", "pituitary"]
PIXEL_SPACING_MM = 0.5
MM2_TO_CM2       = 0.01
MRI_PARAMS = {
    "sequence":        "T1-Weighted Contrast Enhanced",
    "resolution":      "384 x 384",
    "slice_thickness": "5.0 mm",
    "field_strength":  "1.5T",
    "voxel_size":      "0.5 x 0.5 x 5.0 mm",
}

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "").strip()

def get_groq_client():
    if not GROQ_API_KEY:
        raise RuntimeError("Missing GROQ_API_KEY. Add it to your .env file before running reporting.py.")
    return Groq(api_key=GROQ_API_KEY)

groq_client = get_groq_client()

# ════════════════════════════════════════════════════
# MODELS
# ════════════════════════════════════════════════════
print("="*50)
print("LOADING MODELS")
print("="*50)
class_model = tf.keras.models.load_model(CLASS_MODEL_PATH)
seg_model   = tf.keras.models.load_model(SEG_MODEL_PATH, compile=False)
print("✅ Models loaded")

base_model  = class_model.get_layer("efficientnetv2-s")
head_layers = []
reached     = False
for layer in class_model.layers:
    if layer.name == "efficientnetv2-s":
        reached = True; continue
    if reached:
        head_layers.append(layer)

# ════════════════════════════════════════════════════
# UNIVERSAL SANITIZER  ← fixes ALL unicode PDF crashes
# ════════════════════════════════════════════════════
def safe(text):
    if not isinstance(text, str):
        text = str(text)
    for c, r in {
        '\u2014':'-','\u2013':'-','\u2012':'-','\u2010':'-','\u2011':'-',
        '\u2018':"'",'\u2019':"'",'\u201c':'"','\u201d':'"',
        '\u2022':'-','\u2026':'...','\u00b2':'2','\u00b3':'3',
        '\u00b0':' deg','\u00b1':'+/-','\u2192':'->','\u2265':'>=',
        '\u2264':'<=','\u2260':'!=','\u00b5':'u','\u00d7':'x',
    }.items():
        text = text.replace(c, r)
    return text.encode('latin-1', errors='ignore').decode('latin-1')

# ════════════════════════════════════════════════════
# HELPERS
# ════════════════════════════════════════════════════
def load_class_image(path):
    img = tf.keras.utils.load_img(path, target_size=(IMG_SIZE, IMG_SIZE))
    img = tf.keras.utils.img_to_array(img)
    img = effv2_prep(img)
    return np.expand_dims(img, axis=0)

def get_gradcam_heatmap(img_tensor):
    img_tensor_cast = tf.cast(img_tensor, tf.float32)
    conv_output     = base_model(img_tensor_cast, training=False)
    conv_var        = tf.Variable(conv_output)
    with tf.GradientTape() as tape:
        tape.watch(conv_var)
        x = conv_var
        for layer in head_layers:
            x = layer(x)
        class_score = x[:, tf.argmax(x[0])]
    grads = tape.gradient(class_score, conv_var)
    if grads is None:
        return np.zeros((12, 12))
    pooled = tf.reduce_mean(grads, axis=(0,1,2))
    hmap   = conv_output[0] @ pooled[..., tf.newaxis]
    hmap   = tf.squeeze(hmap)
    hmap   = tf.maximum(hmap, 0) / (tf.math.reduce_max(hmap) + 1e-8)
    return hmap.numpy()

def estimate_tumor_size(mask):
    tp    = int(np.sum(mask))
    tot   = mask.shape[0] * mask.shape[1]
    amm2  = tp * (PIXEL_SPACING_MM**2)
    acm2  = amm2 * MM2_TO_CM2
    dcm   = (2 * np.sqrt(amm2 / np.pi)) / 10
    pct   = (tp / (tot * 0.60)) * 100
    vol   = acm2 * (5.0/10)
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    bbox  = None
    if cnts:
        x,y,w,h = cv2.boundingRect(max(cnts, key=cv2.contourArea))
        bbox = {"x":x,"y":y,"w":w,"h":h,
                "width_cm":round(w*PIXEL_SPACING_MM/10,2),
                "height_cm":round(h*PIXEL_SPACING_MM/10,2)}
    return {"tumor_pixels":tp,"area_mm2":round(amm2,2),"area_cm2":round(acm2,4),
            "diameter_cm":round(dcm,3),"tumor_percent":round(pct,2),
            "volume_cm3":round(vol,3),"bbox":bbox}

def analyze_tumor_shape(mask):
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not cnts: return None
    lg   = max(cnts, key=cv2.contourArea)
    area = cv2.contourArea(lg)
    peri = cv2.arcLength(lg, True)
    if area==0 or peri==0: return None
    irr  = min(round(1-(4*np.pi*area)/(peri**2),3),1.0)
    comp = round((peri**2)/(4*np.pi*area),3)
    hull = cv2.convexHull(lg)
    conv = round(area/cv2.contourArea(hull),3) if cv2.contourArea(hull)>0 else 1.0
    ecc  = 0.0
    if len(lg)>=5:
        el  = cv2.fitEllipse(lg)
        a,b = el[1][0]/2, el[1][1]/2
        if max(a,b)>0: ecc = round(np.sqrt(1-(min(a,b)/max(a,b))**2),3)
    bdef = "Poorly defined" if irr>0.5 else ("Moderately defined" if irr>0.3 else "Well-defined")
    rough= "High" if irr>0.5 else ("Moderate" if irr>0.3 else "Low")
    return {"irregularity":irr,"compactness":comp,"convexity":conv,
            "eccentricity":ecc,"border_def":bdef,"roughness":rough}

def detect_mass_effect(mask):
    h,w  = mask.shape
    mid  = w//2
    lt   = int(np.sum(mask[:,:mid]))
    rt   = int(np.sum(mask[:,mid:]))
    tot  = lt+rt
    lat  = "None"
    smm  = 0.0
    if tot>0:
        r   = lt/tot
        lat = "Left hemisphere" if r>0.6 else ("Right hemisphere" if r<0.4 else "Bilateral/Midline")
        smm = round(abs(lt-rt)*(PIXEL_SPACING_MM**2)/(h*PIXEL_SPACING_MM),2)
    comp = "Moderate" if smm>5 else ("Mild" if smm>2 else "None")
    sulf = "Present" if smm>2 else "Absent"
    return {"laterality":lat,"shift_mm":smm,"compression":comp,"sulcal":sulf}

def compute_risk_score(label, confidence, size_info, shape_info, mass_info):
    if label=="no_tumor": return {"score":0.0,"risk":"None","progression_risk":"0%"}
    s  = min(confidence,1.0)*0.25
    s += min(size_info['tumor_percent']/30,1.0)*0.20
    s += min(size_info['volume_cm3']/20,1.0)*0.20
    if shape_info:
        s += shape_info['irregularity']*0.15
        s += (1-shape_info['convexity'])*0.10
    s += min(mass_info['shift_mm']/10,1.0)*0.10
    s  = round(min(s,1.0),3)
    risk = "High" if s>0.7 else ("Moderate" if s>0.4 else "Low")
    prog = f"{int(s*100)}%" if s>0.7 else (f"{int(s*80)}%" if s>0.4 else f"{int(s*60)}%")
    return {"score":s,"risk":risk,"progression_risk":prog}

def compute_confidence_calibration(confidence):
    u = round((1-confidence)*0.5+0.01,3)
    return {"uncertainty":f"+/-{round(u*100,1)}%","cal_score":round(1-u,3)}

def get_severity(label, confidence, tumor_percent):
    if label=="no_tumor": return "None"
    if tumor_percent>20 or confidence>0.95: return "Severe"
    if tumor_percent>10 or confidence>0.80: return "Moderate"
    return "Mild"

def get_recommendation(label, severity):
    if label=="no_tumor": return "No tumor detected. Routine follow-up recommended."
    return {"Mild":"Follow-up MRI in 3 months. Neurology consult.",
            "Moderate":"Urgent neurology consultation within 2 weeks.",
            "Severe":"Immediate neurosurgical referral required."}.get(severity,"Consult specialist.")

def get_clinical_decision(label, severity, mass_info):
    if label=="no_tumor":
        return {"steps":["Routine follow-up in 12 months","No immediate action required"],"urgency":"Low"}
    steps = ["Neurosurgical consultation","Contrast MRI follow-up"]
    if severity=="Severe":
        steps += ["MR Spectroscopy","Perfusion MRI","Surgical planning","Biopsy / Histopathology"]
        urg = "Critical"
    elif severity=="Moderate":
        steps += ["MR Spectroscopy","Neuropsychological assessment"]
        urg = "High"
    else:
        steps += ["PET scan consideration","Neurological evaluation"]
        urg = "Moderate"
    if mass_info['shift_mm']>3: steps.append("Immediate review for mass effect")
    return {"steps":steps,"urgency":urg}

def get_rano_assessment(label, size_info, shape_info):
    if label=="no_tumor": return None
    sc  = "Large" if size_info['diameter_cm']>3 else ("Medium" if size_info['diameter_cm']>1.5 else "Small")
    nec = "Likely present" if (shape_info and shape_info['irregularity']>0.5) else "Not clearly identified"
    enh = "Heterogeneous" if (shape_info and shape_info['irregularity']>0.4) else "Homogeneous"
    grd = "High-Grade (imaging features suggest possible high-grade - histopathological confirmation required)"
    if size_info['diameter_cm']<2 and (not shape_info or shape_info['irregularity']<0.3):
        grd = "Low-Grade (imaging features suggest possible low-grade - histopathological confirmation required)"
    return {"size_cat":sc,"enhancement":enh,"necrosis":nec,"grade":grd}

def clean_llm_text(text):
    text = re.sub(r'#{1,6}\s*','',text)
    text = re.sub(r'\*\*(.*?)\*\*',r'\1',text)
    text = re.sub(r'\*(.*?)\*',r'\1',text)
    text = re.sub(r'`(.*?)`',r'\1',text)
    return safe(text)

# ════════════════════════════════════════════════════
# GROQ
# ════════════════════════════════════════════════════
def generate_llm_report(image_path, label, confidence, size_info, shape_info,
                         mass_info, risk_info, severity, recommendation, rano):
    with open(image_path,"rb") as f:
        img_b64 = base64.b64encode(f.read()).decode("utf-8")
    bbox_t = f"{size_info['bbox']['width_cm']} cm x {size_info['bbox']['height_cm']} cm" if size_info['bbox'] else "N/A"
    rano_t = "" if not rano else f"\n- RANO Size: {rano['size_cat']}\n- Enhancement: {rano['enhancement']}\n- Necrosis: {rano['necrosis']}"
    shape_t= "" if not shape_info else f"\n- Irregularity: {shape_info['irregularity']}\n- Border: {shape_info['border_def']}"
    prompt = f"""You are an expert radiologist AI assistant.

AI FINDINGS:
- Type: {label} | Confidence: {confidence:.2%} | Severity: {severity}
- Area: {size_info['area_cm2']} cm2 | Diameter: {size_info['diameter_cm']} cm | Volume: {size_info['volume_cm3']} cm3
- Brain Coverage: {size_info['tumor_percent']}% | Bounding Box: {bbox_t}
- Laterality: {mass_info['laterality']} | Midline Shift: {mass_info['shift_mm']} mm
- Risk Score: {risk_info['score']} | Growth Risk: {risk_info['risk']}
{shape_t}{rano_t}

Write a structured radiology report with these exact 6 sections:
1. CLINICAL INDICATION
2. IMAGING TECHNIQUE
3. FINDINGS
4. IMPRESSION
5. SEVERITY ASSESSMENT
6. RECOMMENDATIONS

STRICT RULES:
- Plain ASCII only. No em dashes, smart quotes, markdown, bullets, or special symbols.
- Never confirm tumor grade. Say imaging features suggest possible grade only.
- Always state histopathological confirmation is required.
- Keep each section to 2-4 sentences. Total report under 300 words."""
    resp = groq_client.chat.completions.create(
        model="meta-llama/llama-4-scout-17b-16e-instruct",
        messages=[{"role":"user","content":[
            {"type":"image_url","image_url":{"url":f"data:image/jpeg;base64,{img_b64}"}},
            {"type":"text","text":prompt}
        ]}],
        max_tokens=1000
    )
    return clean_llm_text(resp.choices[0].message.content)

# ════════════════════════════════════════════════════
# RISK CHART
# ════════════════════════════════════════════════════
def generate_risk_chart(size_info, risk_info, shape_info, mass_info):
    fig, axes = plt.subplots(1, 3, figsize=(13, 3.2))
    fig.patch.set_facecolor('#ffffff')
    tp = max(min(size_info['tumor_percent'],100),0)
    axes[0].pie([tp,100-tp],labels=['Tumor','Healthy Brain'],
                colors=['#e74c3c','#2ecc71'],autopct='%1.1f%%',
                startangle=90,textprops={'fontsize':8})
    axes[0].set_title('Tumor vs Brain Coverage',fontweight='bold',fontsize=9)
    cats = ['Confidence','Size Risk','Shape Risk','Mass Effect']
    vals = [round(min(risk_info['score']*1.2,1.0),2),
            round(min(size_info['tumor_percent']/30,1.0),2),
            round(shape_info['irregularity'] if shape_info else 0,2),
            round(min(mass_info['shift_mm']/10,1.0),2)]
    cols = ['#e74c3c' if v>0.6 else '#f39c12' if v>0.3 else '#2ecc71' for v in vals]
    bars = axes[1].barh(cats,vals,color=cols,height=0.5)
    axes[1].set_xlim(0,1)
    axes[1].axvline(0.5,color='gray',linestyle='--',alpha=0.5)
    axes[1].set_title('Risk Factor Analysis',fontweight='bold',fontsize=9)
    for bar,v in zip(bars,vals):
        axes[1].text(bar.get_width()+0.02,bar.get_y()+bar.get_height()/2,
                     f'{v:.2f}',va='center',fontsize=7)
    axes[1].set_facecolor('#f8f8f8')
    if shape_info:
        sc = ['Irregularity','Compact.\n(norm)','Eccentricity','1-Convexity']
        sv = [shape_info['irregularity'],min(shape_info['compactness']/3,1.0),
              shape_info['eccentricity'],round(1-shape_info['convexity'],3)]
        axes[2].bar(sc,sv,color=['#9b59b6','#3498db','#1abc9c','#e67e22'],width=0.5)
        axes[2].set_ylim(0,1)
        axes[2].set_facecolor('#f8f8f8')
        for i,v in enumerate(sv):
            axes[2].text(i,v+0.02,f'{v:.2f}',ha='center',fontsize=7)
    else:
        axes[2].text(0.5,0.5,'No tumor',ha='center',va='center')
    axes[2].set_title('Tumor Shape Metrics',fontweight='bold',fontsize=9)
    plt.tight_layout(pad=1.0)
    os.makedirs("/tmp/report_imgs",exist_ok=True)
    path="/tmp/report_imgs/risk_chart.jpg"
    plt.savefig(path,dpi=110,bbox_inches='tight',facecolor='white')
    plt.close()
    return path

# ════════════════════════════════════════════════════
# 2-PAGE PDF  ← completely rewritten, no overflow
# ════════════════════════════════════════════════════
def save_pdf_report(filename, image_path, label, confidence, size_info,
                    shape_info, mass_info, risk_info, cal_info, severity,
                    recommendation, llm_report, clinical, rano,
                    orig, mask_overlay, heatmap, gradcam_overlay):

    SEV = {"Severe":(200,50,50),"Moderate":(220,140,0),
           "Mild":(50,150,50),"None":(50,150,50)}
    SC  = SEV.get(severity,(80,80,80))
    pdf = FPDF()
    pdf.set_auto_page_break(auto=False)   # manual page control

    # ── shared helpers ──────────────────────────────
    def sec(title, y):
        pdf.set_xy(10, y)
        pdf.set_fill_color(20,40,80)
        pdf.set_text_color(255,255,255)
        pdf.set_font("Helvetica","B",8)
        pdf.cell(190, 5.5, safe(f"  {title}"), ln=True, fill=True)
        pdf.set_text_color(0,0,0)
        return y + 6

    def box(x, y, w, h, rgb=(245,248,255)):
        pdf.set_fill_color(*rgb)
        pdf.set_draw_color(200,210,230)
        pdf.rect(x, y, w, h, 'FD')

    def field(x, y, key, val, kw=38, fw=55):
        pdf.set_xy(x, y)
        pdf.set_font("Helvetica","B",7.5)
        pdf.cell(kw, 4.5, safe(f"{key}:"), ln=False)
        pdf.set_font("Helvetica","",7.5)
        pdf.cell(fw, 4.5, safe(str(val)), ln=False)

    # ════════════════════════════════════════════════
    # PAGE 1
    # ════════════════════════════════════════════════
    pdf.add_page()

    # Header
    pdf.set_fill_color(20,40,80); pdf.rect(0,0,210,22,'F')
    pdf.set_text_color(255,255,255)
    pdf.set_font("Helvetica","B",15); pdf.set_xy(10,4)
    pdf.cell(130,8,"AI Brain Tumor Analysis Report",ln=False)
    pdf.set_font("Helvetica","",7)
    pdf.set_xy(10,13); pdf.cell(100,4,safe(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"),ln=False)
    pdf.set_xy(110,13); pdf.cell(90,4,safe(f"File: {filename}"),ln=False)
    pdf.set_text_color(0,0,0)

    # Severity badge
    pdf.set_fill_color(*SC); pdf.rect(10,24,190,7,'F')
    pdf.set_text_color(255,255,255); pdf.set_font("Helvetica","B",8)
    pdf.set_xy(10,25.5)
    pdf.cell(190,4,safe(
        f"  SEVERITY: {severity.upper()}   |   PREDICTION: {label.upper()}"
        f"   |   CONFIDENCE: {confidence:.2%}"
        f"   |   GROWTH RISK: {risk_info['risk'].upper()}"),align="C")
    pdf.set_text_color(0,0,0)

    # ── ANALYSIS SUMMARY ────────────────────────────
    y = 33
    y = sec("ANALYSIS SUMMARY", y)
    box(10, y, 190, 36)
    rows_c1 = [("Tumor Type",label.upper()),("Confidence",f"{confidence:.2%}"),
               ("Uncertainty",cal_info['uncertainty']),("Calibration",str(cal_info['cal_score'])),
               ("Severity",severity)]
    rows_c2 = [("Tumor Area",f"{size_info['area_cm2']} cm2"),
               ("Diameter",f"{size_info['diameter_cm']} cm"),
               ("Est. Volume",f"{size_info['volume_cm3']} cm3"),
               ("Brain Coverage",f"{size_info['tumor_percent']}%"),
               ("Bounding Box",f"{size_info['bbox']['width_cm']}x{size_info['bbox']['height_cm']} cm" if size_info['bbox'] else "N/A")]
    rows_c3 = [("Laterality",mass_info['laterality']),
               ("Midline Shift",f"{mass_info['shift_mm']} mm"),
               ("Compression",mass_info['compression']),
               ("Sulcal Eff.",mass_info['sulcal']),
               ("Aggressiveness",f"{round(risk_info['score'],3)} / 1.0")]
    for i,(k,v) in enumerate(rows_c1):
        field(12,  y+1+i*7, k, v, kw=30, fw=30)
    for i,(k,v) in enumerate(rows_c2):
        field(74,  y+1+i*7, k, v, kw=32, fw=26)
    for i,(k,v) in enumerate(rows_c3):
        field(136, y+1+i*7, k, v, kw=30, fw=32)
    y += 38

    # ── MRI DETAILS ─────────────────────────────────
    y = sec("MRI ACQUISITION DETAILS", y)
    box(10, y, 190, 15)
    field(12, y+1,  "Sequence",        MRI_PARAMS["sequence"],       kw=26, fw=36)
    field(12, y+8,  "Resolution",      MRI_PARAMS["resolution"],     kw=26, fw=36)
    field(76, y+1,  "Slice Thickness", MRI_PARAMS["slice_thickness"],kw=30, fw=28)
    field(76, y+8,  "Field Strength",  MRI_PARAMS["field_strength"], kw=30, fw=28)
    field(142,y+1,  "Voxel Size",      MRI_PARAMS["voxel_size"],     kw=26, fw=38)
    field(142,y+8,  "Note",            "Standard assumed values",    kw=26, fw=38)
    y += 17

    # ── VISUAL ANALYSIS ──────────────────────────────
    y = sec("VISUAL ANALYSIS", y)
    tmp = "/tmp/report_imgs"; os.makedirs(tmp,exist_ok=True)
    def sv(arr,name,bgr=True):
        p=f"{tmp}/{name}.jpg"
        if bgr: cv2.imwrite(p,arr)
        else:   plt.imsave(p,arr,cmap="jet")
        return p
    paths=[sv(orig,"orig"),sv(mask_overlay,"mask"),
           sv(heatmap,"heatmap",bgr=False),sv(gradcam_overlay,"gcam")]
    lbls=["Original MRI","Segmentation","GradCAM Heatmap","GradCAM Overlay"]
    iw,ih=45,40
    for i,(p,l) in enumerate(zip(paths,lbls)):
        x=11+i*(iw+2)
        pdf.image(p,x=x,y=y,w=iw,h=ih)
        pdf.set_font("Helvetica","B",6.5); pdf.set_xy(x,y+ih+0.5)
        pdf.cell(iw,3.5,safe(l),align="C")
    y += ih+5

    # ── SHAPE | MASS | RISK  (3-panel compact row) ──
    y = sec("SHAPE ANALYSIS   |   MASS EFFECT   |   RISK SCORE", y)
    box(10, y, 190, 24)
    if shape_info:
        field(12,y+1,  "Irregularity",str(shape_info['irregularity']),kw=24,fw=18)
        field(12,y+8,  "Compactness", str(shape_info['compactness']), kw=24,fw=18)
        field(12,y+15, "Convexity",   str(shape_info['convexity']),   kw=24,fw=18)
        field(12,y+20, "Border",      shape_info['border_def'],       kw=24,fw=18)
    field(78, y+1,  "Laterality",  mass_info['laterality'],          kw=22,fw=26)
    field(78, y+8,  "Shift",       f"{mass_info['shift_mm']} mm",    kw=22,fw=26)
    field(78, y+15, "Compression", mass_info['compression'],         kw=22,fw=26)
    field(78, y+20, "Sulcal",      mass_info['sulcal'],              kw=22,fw=26)
    # Risk with colour
    pdf.set_xy(138,y+1);  pdf.set_font("Helvetica","B",7.5)
    pdf.cell(28,4.5,"Aggress. Score:",ln=False)
    pdf.set_text_color(*SC); pdf.cell(22,4.5,safe(f"{round(risk_info['score'],3)} / 1.0"),ln=False)
    pdf.set_text_color(0,0,0)
    pdf.set_xy(138,y+8);  pdf.set_font("Helvetica","B",7.5)
    pdf.cell(28,4.5,"Growth Risk:",ln=False)
    pdf.set_text_color(*SC); pdf.cell(22,4.5,safe(risk_info['risk']),ln=False)
    pdf.set_text_color(0,0,0)
    field(138,y+15,"Progression", risk_info['progression_risk'],kw=28,fw=20)
    field(138,y+20,"Uncertainty", cal_info['uncertainty'],      kw=28,fw=20)
    y += 26

    # ── RANO ────────────────────────────────────────
    if rano:
        y = sec("RANO CRITERIA ASSESSMENT", y)
        box(10, y, 190, 18)
        field(12, y+1,  "Size Category", rano['size_cat'],   kw=28,fw=28)
        field(12, y+9,  "Enhancement",   rano['enhancement'],kw=28,fw=28)
        field(80, y+1,  "Necrosis",      rano['necrosis'],   kw=22,fw=36)
        pdf.set_xy(80, y+9)
        pdf.set_font("Helvetica","B",7); pdf.cell(22,4,"Grade:",ln=False)
        pdf.set_font("Helvetica","B",7); pdf.set_text_color(*SC)
        pdf.multi_cell(106,4,safe(rano['grade']))
        pdf.set_text_color(0,0,0)
        y += 20

    # ── CLINICAL DECISION ───────────────────────────
    y = sec("CLINICAL DECISION SUPPORT", y)
    n   = len(clinical['steps'])
    mid = (n+1)//2
    ch  = mid*5.5 + 12
    box(10,y,190,ch)
    pdf.set_xy(12,y+1.5); pdf.set_font("Helvetica","B",7.5)
    pdf.cell(26,4.5,"Urgency Level:",ln=False)
    pdf.set_font("Helvetica","B",8); pdf.set_text_color(*SC)
    pdf.cell(30,4.5,safe(clinical['urgency'].upper()),ln=False)
    pdf.set_text_color(0,0,0)
    for i,step in enumerate(clinical['steps']):
        col = 0 if i<mid else 1
        row = i if i<mid else i-mid
        pdf.set_xy(14+col*95, y+9+row*5.5)
        pdf.set_font("Helvetica","",7.5)
        pdf.cell(90,4.5,safe(f"[+]  {step}"))
    y += ch+2

    # ── RISK CHARTS ─────────────────────────────────
    y = sec("RISK VISUALIZATION", y)
    chart = generate_risk_chart(size_info, risk_info, shape_info, mass_info)
    pdf.image(chart,x=10,y=y,w=190,h=50)
    y += 52

    # Footer p1
    pdf.set_fill_color(20,40,80); pdf.rect(0,285,210,12,'F')
    pdf.set_text_color(255,255,255)
    pdf.set_font("Helvetica","I",6.5); pdf.set_xy(10,287)
    pdf.cell(170,4,"AI-generated report. Must be reviewed by a qualified medical professional before clinical use.")
    pdf.set_font("Helvetica","B",7); pdf.set_xy(185,287)
    pdf.cell(15,4,"Page 1",align="R")
    pdf.set_text_color(0,0,0)

    # ════════════════════════════════════════════════
    # PAGE 2  –  LLM Radiology Report
    # ════════════════════════════════════════════════
    pdf.add_page()
    pdf.set_fill_color(20,40,80); pdf.rect(0,0,210,16,'F')
    pdf.set_text_color(255,255,255)
    pdf.set_font("Helvetica","B",12); pdf.set_xy(10,4)
    pdf.cell(0,8,"AI Generated Radiology Report",ln=False)
    pdf.set_font("Helvetica","",7); pdf.set_xy(140,6)
    pdf.cell(0,4,safe(f"File: {filename}"),ln=False)
    pdf.set_text_color(0,0,0)
    pdf.set_xy(10,18); pdf.set_font("Helvetica","I",7)
    pdf.set_text_color(130,130,130)
    pdf.cell(0,4,"Note: AI-generated imaging findings. Histopathological confirmation is required for definitive diagnosis.",ln=True)
    pdf.set_text_color(0,0,0)

    y2 = 24
    for line in llm_report.split("\n"):
        line = safe(line.strip())
        if not line: y2 += 2; continue
        if y2 > 278: break
        is_hdr = any(line.startswith(h) for h in ["1.","2.","3.","4.","5.","6."])
        if is_hdr:
            y2 += 1
            pdf.set_fill_color(230,235,255)
            pdf.set_font("Helvetica","B",8.5)
            pdf.set_text_color(20,40,80)
            pdf.set_xy(10,y2)
            pdf.cell(190,5.5,f"  {line}",fill=True)
            pdf.set_text_color(0,0,0)
            y2 += 7
        else:
            pdf.set_font("Helvetica","",8)
            pdf.set_text_color(30,30,30)
            pdf.set_xy(12,y2)
            pdf.multi_cell(186,4.5,line)
            y2 = pdf.get_y()+1

    # Footer p2
    pdf.set_fill_color(20,40,80); pdf.rect(0,285,210,12,'F')
    pdf.set_text_color(255,255,255)
    pdf.set_font("Helvetica","I",6.5); pdf.set_xy(10,287)
    pdf.cell(170,4,"AI-generated report. Must be reviewed by a qualified medical professional before clinical use.")
    pdf.set_font("Helvetica","B",7); pdf.set_xy(185,287)
    pdf.cell(15,4,"Page 2",align="R")
    pdf.set_text_color(0,0,0)

    # ── Save ────────────────────────────────────────
    safe_name = os.path.splitext(filename)[0]
    ts        = datetime.now().strftime('%Y%m%d%H%M%S')
    out       = os.path.join(REPORT_DIR, f"{safe_name}_{ts}_mri_report.pdf")
    pdf.output(out)
    print(f"  📄 PDF saved: {out}")
    return out

# ════════════════════════════════════════════════════
# MAIN PIPELINE  (first image only)
# ════════════════════════════════════════════════════
print("\n"+"="*50)
print("RUNNING FULL PIPELINE - FIRST IMAGE ONLY")
print("="*50)

all_files = [f for f in os.listdir(TEST_DIR)
             if f.lower().endswith((".png",".jpg",".jpeg",".bmp"))]
print(f"Found {len(all_files)} images - processing first one only\n")
passed = failed = 0

for file in all_files[:1]:
    image_path = os.path.join(TEST_DIR, file)
    print("="*50)
    print(f"Processing: {file}")
    try:
        print("[STEP 1] Classification...")
        orig       = cv2.resize(cv2.imread(image_path),(IMG_SIZE,IMG_SIZE))
        img_class  = load_class_image(image_path)
        img_tensor = tf.convert_to_tensor(img_class)
        preds      = class_model(img_tensor,training=False)[0].numpy()
        class_id   = np.argmax(preds)
        label      = CLASS_NAMES[class_id]
        confidence = preds[class_id]
        print(f"  ✅ {label} ({confidence:.2%})")

        print("[STEP 2] Segmentation...")
        img_seg = cv2.resize(cv2.imread(image_path,cv2.IMREAD_GRAYSCALE),(SEG_SIZE,SEG_SIZE))
        img_seg = np.expand_dims(img_seg/255.0,(0,-1))
        mask    = (seg_model(img_seg,training=False)[0].numpy()>0.5).astype(np.uint8)
        mask    = cv2.resize(mask,(IMG_SIZE,IMG_SIZE))
        print("  ✅ Mask generated")

        print("[STEP 3] GradCAM...")
        heatmap = get_gradcam_heatmap(img_tensor)
        print("  ✅ Heatmap generated")

        print("[STEP 4] Computing Metrics...")
        size_info  = estimate_tumor_size(mask)
        shape_info = analyze_tumor_shape(mask)
        mass_info  = detect_mass_effect(mask)
        risk_info  = compute_risk_score(label,confidence,size_info,shape_info,mass_info)
        cal_info   = compute_confidence_calibration(confidence)
        severity   = get_severity(label,confidence,size_info['tumor_percent'])
        rec        = get_recommendation(label,severity)
        clinical   = get_clinical_decision(label,severity,mass_info)
        rano       = get_rano_assessment(label,size_info,shape_info)
        print(f"  ✅ Area:{size_info['area_cm2']}cm2 | Vol:{size_info['volume_cm3']}cm3 | Sev:{severity} | Risk:{risk_info['risk']}")

        print("[STEP 5] Generating Report via Groq...")
        llm_report = generate_llm_report(image_path,label,confidence,size_info,
                                          shape_info,mass_info,risk_info,severity,rec,rano)
        print("  ✅ Report generated")

        # Build overlays
        mask_vis     = np.uint8(mask*255)
        mask_color   = cv2.applyColorMap(mask_vis,cv2.COLORMAP_HOT)
        mask_overlay = cv2.addWeighted(orig,0.7,mask_color,0.3,0)
        if size_info['bbox']:
            b=size_info['bbox']
            cv2.rectangle(mask_overlay,(b['x'],b['y']),(b['x']+b['w'],b['y']+b['h']),(0,255,0),2)
            cv2.putText(mask_overlay,f"{size_info['diameter_cm']}cm",(b['x'],b['y']-8),
                        cv2.FONT_HERSHEY_SIMPLEX,0.6,(0,255,0),2)
        hmap_r  = cv2.resize(heatmap,(IMG_SIZE,IMG_SIZE))
        hmap_c  = cv2.applyColorMap(np.uint8(255*hmap_r),cv2.COLORMAP_JET)
        gcam_ov = cv2.addWeighted(orig,0.6,hmap_c,0.4,0)

        save_pdf_report(file,image_path,label,confidence,size_info,
                        shape_info,mass_info,risk_info,cal_info,severity,
                        rec,llm_report,clinical,rano,
                        orig,mask_overlay,hmap_r,gcam_ov)

        # Notebook preview
        fig,axes=plt.subplots(1,4,figsize=(20,5))
        fig.suptitle(f"{file}  |  {label} ({confidence:.2%})  |  Vol:{size_info['volume_cm3']}cm3  |  Sev:{severity}  |  Risk:{risk_info['risk']}",fontsize=10)
        axes[0].imshow(cv2.cvtColor(orig,cv2.COLOR_BGR2RGB)); axes[0].set_title("Original MRI"); axes[0].axis("off")
        axes[1].imshow(cv2.cvtColor(mask_overlay,cv2.COLOR_BGR2RGB)); axes[1].set_title(f"Segmentation | D:{size_info['diameter_cm']}cm"); axes[1].axis("off")
        axes[2].imshow(hmap_r,cmap="jet"); axes[2].set_title("GradCAM Heatmap"); axes[2].axis("off")
        axes[3].imshow(cv2.cvtColor(gcam_ov,cv2.COLOR_BGR2RGB)); axes[3].set_title("GradCAM Overlay"); axes[3].axis("off")
        plt.tight_layout(); plt.show()
        passed += 1

    except Exception as e:
        import traceback
        print(f"  ❌ FAILED: {e}")
        traceback.print_exc()
        failed += 1

print("\n"+"="*50)
print("FINAL SUMMARY")
print("="*50)
print(f"  Total Processed : 1 of {len(all_files)}")
print(f"  ✅ Passed       : {passed}")
print(f"  ❌ Failed       : {failed}")
print(f"  📁 Report saved : {REPORT_DIR}")
print("="*50)
