# -*- coding: utf-8 -*-
"""classification_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132GFqf5CBUnjM9yE9tBhpe90T2ZAiN6K

Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""Imports"""

import tensorflow as tf
import numpy as np

# ================== PREPROCESS ==================
from tensorflow.keras.applications.mobilenet_v3 import preprocess_input as mnv3_prep
from tensorflow.keras.applications.convnext import preprocess_input as convnext_prep
from tensorflow.keras.applications.efficientnet_v2 import preprocess_input as effv2_prep

# ================== CONFIG ==================
IMG_SIZE = 384  # MUST match training

# ✅ CORRECT CLASS ORDER (FROM TRAINING)
CLASS_NAMES = [
    "glioma",
    "meningioma",
    "no_tumor",
    "pituitary"
]

# ================== IMAGES TO TEST ==================
IMAGE_PATHS = {
    "glioma": "/content/drive/MyDrive/Project work/Test Data/test_glioma.jpg",
    "meningioma": "/content/drive/MyDrive/Project work/Test Data/test_meningioma.jpg",
    "pituitary": "/content/drive/MyDrive/Project work/Test Data/test_pituitary.jpg",
    "no_tumor": "/content/drive/MyDrive/Project work/Test Data/test_no tumor.jpg"
}

# ================== MODEL PATHS ==================
MODEL_PATHS = {
    "MobileNetV3": "/content/drive/MyDrive/Project work/models/Classification/tumor_mobilenet_v3.keras",
    "ConvNeXt-Tiny": "/content/drive/MyDrive/Project work/models/Classification/Tumor_convnext_tiny_tumor.keras",
    "EfficientNetV2-S": "/content/drive/MyDrive/Project work/models/Classification/Tumor_v2s_clean.keras",
}

# ================== IMAGE LOADER ==================
def load_image(path):
    img = tf.keras.utils.load_img(
        path,
        target_size=(IMG_SIZE, IMG_SIZE)
    )
    img = tf.keras.utils.img_to_array(img)
    img = tf.expand_dims(img, axis=0)
    return img

PREPROCESS = {
    "MobileNetV3": mnv3_prep,
    "ConvNeXt-Tiny": convnext_prep,
    "EfficientNetV2-S": effv2_prep,
}

# ================== LOAD MODELS ==================
models = {}

for name, path in MODEL_PATHS.items():
    print(f"Loading {name}...")
    models[name] = tf.keras.models.load_model(path)

print("All models loaded successfully.\n")

# ================== MANUAL TESTING ==================
print("🧠 Tumor Classification – Manual Image Testing")
print("=" * 60)

for true_label, img_path in IMAGE_PATHS.items():

    print(f"\nTesting image: {true_label}")
    print("-" * 60)

    img = load_image(img_path)

    for model_name, model in models.items():

        img_proc = PREPROCESS[model_name](img)
        preds = model.predict(img_proc, verbose=0)[0]

        idx = np.argmax(preds)
        pred_label = CLASS_NAMES[idx]
        confidence = preds[idx]

        print(
            f"{model_name:18s} → "
            f"Pred: {pred_label:12s} | "
            f"Conf: {confidence:.4f}"
        )